### ISSUE TITLE
如何下载4k视频？

### ISSUE THREAD

**Issue by leixjtu** [leiurayer/downkyi#100]
利用大佬开发的这个项目，在不登陆账号的情况下可以下载到1080p的视频，但是如果想下载4k视频，那么是不是要冲会员，而且从原理上来讲，下载的4k视频的链接与1080p会不会不一样？希望可以在简介里添加下载4k视频的步骤

**Comment by FlySelfLog** [comment]
是的，不同画质、编码的下载链接都不一样，每一次请求的链接也会不同，无法预测，所以想要下载4k，只能用会员账号

**Comment by leixjtu** [comment]
感谢大佬提醒，用会员账号这个也能理解, 毕竟b站也是要恰饭的。还有一个问题是，如果想实现远程下载的话，我看有些类似的软件可以实现解析视频后有新的下载的地址，然后将这个地址复制到浏览器就可以在浏览器下载。那么大佬能够考虑添加一个功能，就是在解析视频之后，可以显示解析后的链接。如果有解析后视频的链接的话，直接复制此链接就可以实现远程下载。
或者此项目如果有linux版本的话（deb文件或者docker镜像）那么会更好，在服务器端就可以直接使用，远程下载。总而言之十分感谢大佬开发的这个项目.

**Comment by Sikaorensheng** [comment]
> 感谢大佬提醒，用会员账号这个也能理解, 毕竟b站也是要恰饭的。还有一个问题是，如果想实现远程下载的话，我看有些类似的软件可以实现解析视频后有新的下载的地址，然后将这个地址复制到浏览器就可以在浏览器下载。那么大佬能够考虑添加一个功能，就是在解析视频之后，可以显示解析后的链接。如果有解析后视频的链接的话，直接复制此链接就可以实现远程下载。
> 或者此项目如果有linux版本的话（deb文件或者docker镜像）那么会更好，在服务器端就可以直接使用，远程下载。总而言之十分感谢大佬开发的这个项目.

我记得哔哩哔哩助手有你说的这个功能，你可以去试一试。
