### ISSUE TITLE
无法登陆账号

### ISSUE THREAD

**Issue by 596142041** [leiurayer/downkyi#1000]
![微信截图_20240103233211](https://github.com/leiurayer/downkyi/assets/4958182/1b94d412-00f2-4b49-a820-f862cc258e1c)
[20240103(0).log](https://github.com/leiurayer/downkyi/files/13820786/20240103.0.log)
![微信图片_20240103233323](https://github.com/leiurayer/downkyi/assets/4958182/96d3945a-e02a-43e9-a640-87455b127538)
无法登陆账号，APP上面还提示域名不在B站下。这是啥原因啊

**Comment by yaobiao131** [comment]
这个应该就是你自己网络的问题了

**Comment by 596142041** [comment]
已经确认是网络问题。
