### ISSUE TITLE
下载的视频没有声音

### ISSUE THREAD

**Issue by witallwang** [leiurayer/downkyi#1001]
版本1.6.1，所有下载的视频都没有声音，在设置页面也没有相关设置，请问是我打开方式不对么？谢谢

**Comment by tamulamayu** [comment]
看到你说的 我才发现我下了一天的视频都是没声音..

**Comment by hydrogen-shelter** [comment]
我翻了下一周内的下载视频，都是有声音的，重下软件试试？

**Comment by witallwang** [comment]
我在设置里取消勾选音频后重新选择就好了。
