### ISSUE TITLE
DowKyi1.4.0同时下载多文件或某些视频会经常闪退无法正常使用

### ISSUE THREAD

**Issue by Gitter3Xey** [leiurayer/downkyi#104]
尝试过一次性过下载 敖厂长 极客湾 UP主的全部视频 ，蜡笔小心番剧第一季 时都会出现闪退情况，重新打开时部分下载任务会继续下载，但是会丢失很多没有被下载的任务。 

下载 敖厂长的全部视频时，遇到这个任务100%必闪退  https://www.bilibili.com/video/BV1es411o7uR   （单独下载就没事） ，只列举出来了其中一个，还有很多。。。
感觉一次性下载UP的全部视频如果有上百的稿件以上的没有哪一个UP是可以一次性全部成功下载的  ，或者番剧里有很多集 的也是的。。
单独下载某一个视频或者有多P的不会闪退。
如果下载到机械硬盘里软件会卡卡的，特别是多任务多线程下载有可能也会造成崩溃，建议下载到固态里。
最后感谢软件作者，这已经是众多下载B站视频工具里最好用的一个了。

**Comment by mataszhang** [comment]
我也遇到这样的情况，如果下载超过300个内容的就会非常卡。CPU的使用率也没有很高，就是非常的慢，而且会闪退
