### ISSUE TITLE
1.6.1，1.6.0不能解析或者解析后下载失败，1.5.9不能登录，有什么比较稳定的版本么

### ISSUE THREAD

**Issue by AndrewMurfman** [leiurayer/downkyi#1048]

**Comment by moejun** [comment]
确实，我也是点解析后没有反应，我还以为是我网络问题。。。

**Comment by Sakrao** [comment]
1.6.1登录后换1.5.9覆盖

**Comment by FB208** [comment]
> 1.6.1登录后换1.5.9覆盖

太机智了，成功解决

**Comment by AndrewMurfman** [comment]
> > 1.6.1登录后换1.5.9覆盖
> 
> 太机智了，成功解决

大佬 怎么覆盖？不会操作啊

**Comment by choices7** [comment]
> 1.6.1登录后换1.5.9覆盖

请问怎么换呢，大佬可以说下吗

**Comment by AndrewMurfman** [comment]
> > 1.6.1登录后换1.5.9覆盖
> 
> 请问怎么换呢，大佬可以说下吗

登录之后安装目录里面会有Config目录，复制过去覆盖就行了

**Comment by choices7** [comment]
> > > 1.6.1登录后换1.5.9覆盖
> > 
> > 
> > 请问怎么换呢，大佬可以说下吗
> 
> 登录之后安装目录里面会有Config目录，复制过去覆盖就行了

感谢大佬，已成功解决
