### ISSUE TITLE
新功能的小建议

### ISSUE THREAD

**Issue by huissv** [leiurayer/downkyi#11]
不知道是否可以做到视频+弹幕+（评论区）的抓取下载呢（以爬虫功能拉实现？）
因为，发现b站收藏夹部分视频被和谐了，虽然也下载了视频，但实在可惜有趣的弹幕和评论区（这才是灵魂哇）

另外也不清楚现在有无支持弹幕的播放器（O-O

不知道大大如何看待这个小建议

**Comment by huissv** [comment]
另外，还有一个功能小建议，实现可以用朋友的大会员账号下载自己的收藏夹视频不（雾

**Comment by huissv** [comment]
弹幕下载，这个chrome插件可做到 哔哩哔哩助手：bilibili.com 综合辅助扩展  https://chrome.google.com/webstore/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B%EF%BC%9Abilibilicom-%E7%BB%BC%E5%90%88%E8%BE%85%E5%8A%A9%E6%89%A9%E5%B1%95/kpbnombpnpcffllnianjibmpadjolanh?utm_source=chrome-ntp-icon

**Comment by huissv** [comment]
或者 greasy fork 上的脚本也可以：bilibili merged flv+mp4+ass+enhance 
Github 地址: https://github.com/Xmader/bilitwin
Greasy Fork 地址: https://greasyfork.org/scripts/372516

**Comment by huissv** [comment]
也或者这个脚本： https://github.com/the1812/Bilibili-Evolved

**Comment by FlySelfLog** [comment]
弹幕下载已经部分实现了，抓取评论也有计划做，不过实在是精力有限，很难短时间内全部实现了，后面会慢慢跟进的
