### ISSUE TITLE
下载大量视频后，无法解析

### ISSUE THREAD

**Issue by instinct2m** [leiurayer/downkyi#123]
**在大量下载视频之后**，就会出现解析失败，再去到官网bilibili中观看 ，
会提示"非常抱歉，本视频由于以下原因.........." ，
但其实不是视频真的被封了或者下架了，过半小时左右去bilibili又可以接着看视频，
但是再用下载器下载视频时，就又会陷入解析失效，视频提示非常抱歉......的循环状态。
![image](https://user-images.githubusercontent.com/32565852/131625214-816ff558-08dd-4716-8f58-5f49292e7cee.png)

![image](https://user-images.githubusercontent.com/32565852/131624840-8c49c057-9ca9-4cf5-8f7d-3a239db889a8.png)

**Comment by leiurayer** [comment]
B站有反爬虫机制，短时间内大量请求会暂时封禁，过一会就好了
