### ISSUE TITLE
无法加载登录二维码

### ISSUE THREAD

**Issue by wan12cf** [leiurayer/downkyi#1242]
1.5.9版本无法加载
1.6.1版本无法加载
按照https://github.com/leiurayer/downkyi/issues/1189]
(https://github.com/yaobiao131/downkyicore)
里面提到的yaobiao131/downkyicore，下载1.0.16后可以扫码
不明白为什么
试过两台电脑都有这个问题，怀疑可能和我的梯子或其他环境有关系但无法定位。
已经试过梯子开全局和不开，均无法解决问题。两台电脑的网络环境分别是北京电信、北京联通，系统windows 10不同版本，梯子用的同一个
希望开发者能帮忙找到问题原因，感谢。我更愿意使用这个软件而不是复制品
![捕获](https://github.com/user-attachments/assets/79f4b3f7-83a4-4815-a3ed-17e75a0a0dd9)

**Comment by wan12cf** [comment]
这是从上文提到的yaobiao131/downkyicore中下载的1.0.16，可以扫码
![捕获2](https://github.com/user-attachments/assets/ccfb06d1-f43c-4abb-8eb4-08fb36e58f98)

**Comment by duanygithub** [comment]
开发者那边似乎出了点问题，我提的pr已经挂了俩月了也没被merge。二维码无法正常显示的具体原因可以看我写的issue #1171

**Comment by jdnjk** [comment]
#1171

**Comment by wan12cf** [comment]
> 开发者那边似乎出了点问题，我提的pr已经挂了俩月了也没被merge。二维码无法正常显示的具体原因可以看我写的issue #1171

谢谢，你好厉害，真的找到了根源

**Comment by wan12cf** [comment]
大家看3楼吧，duanygithub找到了故障原因并给出了修复文件。谢谢大家
