### ISSUE TITLE
下载的弹幕时间轴不正确

### ISSUE THREAD

**Issue by PaperCube** [leiurayer/downkyi#126]
当下载时间超过1小时的视频弹幕时，可以看到超过一小时的部分时间轴显示为：
```
Dialogue: -1,0:59:44.18,0:59:58.18,Danmaku,,0000,0000,0000,,{\move(2120, 400, -200, 400)\3c&H000000} ...
Dialogue: -1,0:59:44.46,1:60:00.46,Danmaku,,0000,0000,0000,,{\move(2270, 750, -350, 750)\3c&H000000} ...
Dialogue: -1,0:59:45.04,1:60:02.04,Danmaku,,0000,0000,0000,,{\move(2345, 200, -425, 200)\3c&H000000} ...
...
Dialogue: -1,2:127:25.93,2:127:41.93,Danmaku,,0000,0000,0000,,{\move(2245, 150, -325, 150)\3c&H000000} ...
```
导致在对应位置无法被播放器正确播放。
若我的理解正确，形如 `1:60:00.46` 的时间轴应为 `1:00:00.46`。

**Comment by aifreedom** [comment]
看了下代码, 是在格式化时间轴的时候, 没有把超过60分钟的分钟数对60取模. 修起来应该很简单, 我开了个PR (https://github.com/leiurayer/downkyi/pull/219), 但因为这个repo没有工程文件, 没办法在本地编译验证是否已经修复.

我写了个简单的Python脚本来修复过去已经下载了的ass文件, 可以在这里下载使用 https://gist.github.com/aifreedom/cad44f3866480ca6b46bba71d5d73132

**注意**: 我只用很少的几个字幕文件做了测试, 请在用这个脚本修复前, 自行备份之前的ass文件. 作者不对因使用该脚本造成的数据丢失等后果负责.
