### ISSUE TITLE
DownKyi-1.4.0.zip包解压失败，提示未知方式，如图，这是怎么回事呀

### ISSUE THREAD

**Issue by liuchuanv** [leiurayer/downkyi#128]
* 解压1.3.7包也是这样。
* 也安装了 .NET Framework 4.8 
![image](https://user-images.githubusercontent.com/19567697/133196310-660278d9-6d0c-4bd7-931e-dcaa6ae7e69b.png)

**Comment by leiurayer** [comment]
用7zip解压试试
