### ISSUE TITLE
关于增加文件命名选项的建议

### ISSUE THREAD

**Issue by yanph2003** [leiurayer/downkyi#133]
希望可以增加自定义命名选项
一个分P视频的每一P都有“总视频名”“分集名”等属性，希望可以自定义下载后文件名的格式，比如用%n代表总文件名，%p代表分p名，%a/%b代表av/bv号，%u代表up主，%t代表上传时间等等，那么对于视频av333069的第2P应用命名规则
`【%u】%n_%p※%a@%t`
可得文件名（不包含扩展名）为：
`【純白】【洛天依】唱给雅音宫羽【原创曲PV付】_在耳邊輕唱※av333069@2012-8-12`

**Comment by leiurayer** [comment]
有这个计划，正在开发1.5版，重构了整个程序，会在1.5的某次更新加入这个功能，
