### ISSUE TITLE
【必看】各位，如果要提交问题和PR前请先看此Issues

### ISSUE THREAD

**Issue by Aarondongsq** [leiurayer/downkyi#1339]
看 #1194
我直呼NB，一直有片哥在创建新的垃圾Issues，炫耀技术，发个新的占个位

我真心希望片哥收敛一点，GitHub是开源社区不是传片社区！要传也去论坛传！我们并不是不知道你找资源厉害！
~~不过我觉得那些片哥用这个视频更好：~~

https://github.com/user-attachments/assets/eaf7063d-5b88-42ca-9244-d15f7378db77

**Comment by jdnjk** [comment]
你是可以知道片哥的威力

**Comment by Aarondongsq** [comment]
> 你是可以知道片哥的威力

会不会是机器人在搞事？

**Comment by jdnjk** [comment]
> > 你是可以知道片哥的威力
> 
> 会不会是机器人在搞事？

y，完全可以使用api滥用的

**Comment by Aarondongsq** [comment]
> > > 你是可以知道片哥的威力
> > 
> > 
> > 会不会是机器人在搞事？
> 
> y，完全可以使用api滥用的

现在啥，都有GPT了，可以通过AI破解验证码，我真心希望GitHub立即封这些垃圾号

**Comment by jdnjk** [comment]
> > > > 你是可以知道片哥的威力
> > > 
> > > 
> > > 会不会是机器人在搞事？
> > 
> > y，完全可以使用api滥用的
> 
> 现在啥，都有GPT了，可以通过AI破解验证码，我真心希望GitHub立即封这些垃圾号，而且创建时间集合至昨天
> 而据我所知，那些片哥喜欢在停更的项目上发片

滥用过度的基本被自动封禁了

**Comment by aaronkeai** [comment]
我的妈呀，别这么好笑好吗

**Comment by Aarondongsq** [comment]
> > > > > 你是可以知道片哥的威力
> > > > 
> > > > 
> > > > 会不会是机器人在搞事？
> > > 
> > > 
> > > y，完全可以使用api滥用的
> > 
> > 
> > 现在啥，都有GPT了，可以通过AI破解验证码，我真心希望GitHub立即封这些垃圾号，而且创建时间集合至昨天
> > 而据我所知，那些片哥喜欢在停更的项目上发片
> 
> 滥用过度的基本被自动封禁了

那让我拭目以待

**Comment by Aarondongsq** [comment]
他娘的又被片哥挡住了，又来卖片，将会关掉此Issues
