### ISSUE TITLE
【必看】提交Issues和PR前，请先看这里！（去你娘的片哥）

### ISSUE THREAD

**Issue by Aarondongsq** [leiurayer/downkyi#1363]
所有问题看 #1194 
又被片哥挡住了，这么喜欢卖片吗？我真的服了，一群自以为是的人，挂这个机器人以为想干啥就干啥的，帮助做好事不敢，非要做这样恶心人的事情，我真的服了，希望 @GitHub 赶紧管一下这些人，足够牛逼的

~有没有可能，这些片哥是这个厂子里来的：~

https://github.com/user-attachments/assets/50e92aeb-934d-4dc0-859d-6a0e71ac8cbb

**Comment by aaronkeai** [comment]
那些片哥牛逼，我真的不明白他们为何要干这样的事

**Comment by Aarondongsq** [comment]
他妈的，我管不住了，此Issues将会关闭
