### ISSUE TITLE
疑似接口API失效

### ISSUE THREAD

**Issue by ANYLNK** [leiurayer/downkyi#161]
今日突然出现无法下载视频的情况，解析后下载提示没有选中项符合下载要求

PS：同时用you-get进行了测试，也报错，其中debug数据显示current_quality = playinfo['data']['quality'] or None  # 0 indicates an error, fallback to None
KeyError: 'data'，希望能够提供参考

检查更新也总是失败，系统为Win11，软件版本是1.4.0

**Comment by ANYLNK** [comment]
给一个隔壁修好这个问题的解决方案链接吧https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

**Comment by wangfeng35** [comment]
> 给一个隔壁修好这个问题的解决方案链接吧https://raw.githubusercontent.com/rfiacne/you-get/460760ddc8fc860392b562986c6c1047c8856641/src/you_get/extractors/bilibili.py

还有能图形化下载的么
