### ISSUE TITLE
最新版zip压缩包是损坏的，无法解压。

### ISSUE THREAD

**Issue by glv1at118** [leiurayer/downkyi#169]

**Comment by glv1at118** [comment]
None of the versions is working. All broken.

**Comment by leiurayer** [comment]
试试7zip解压

**Comment by RowlingJ** [comment]
我现在用WinRAR解压是可以的

**Comment by hwc0919** [comment]
windows资源管理器，git bash自带的 unzip, 都无法解压缩。7zip可以解压缩。作者应该考虑一下别造成这么大的限制。
