### ISSUE TITLE
弹幕文件与视频不同名称，导致播放器无法自动加载弹幕

### ISSUE THREAD

**Issue by RowlingJ** [leiurayer/downkyi#170]
希望可以为字幕文件也加上视频文件后面的清晰度，使得播放器能够自动加载弹幕

**Comment by Glan7** [comment]
@leiurayer 同时有另外一个请求，【启用视频编号】的时候，字幕文件也加上编号。遇到的场景是：合集视频下载，up主设置的文件没有编码，必须选择【启用视频编号】，现在的视频文件有编号，字幕文件没有编号。
