### ISSUE TITLE
查询用户频道中的视频 (直播回放无法解析)

### ISSUE THREAD

**Issue by septzhjie** [leiurayer/downkyi#185]
**说明: 软件版本1.4.0; 运行系统:win10
问题:无法解析 频道-直播回放** 
![image](https://user-images.githubusercontent.com/44011893/145988768-3011411b-2003-46f7-a35e-306cf714670a.png)
**判断:请求接口路径问题  (浏览器直接get 404)**
![](https://user-images.githubusercontent.com/44011893/145987801-dbaa6863-4c44-48cc-808c-3faa7de23d3a.png)
**尝试: 添加请求参数 ctype=1  有数据**
![image](https://user-images.githubusercontent.com/44011893/145989071-ca319452-28bb-4c53-ad62-573f1839d90a.png)

**Comment by leiurayer** [comment]
感谢提供

**Comment by Honglong22** [comment]
> 感谢提供

大佬有看到我提的两条意见吗？？可以更新增加吗？？

**Comment by leiurayer** [comment]
频道改为合集和列表了
