### ISSUE TITLE
无法下载弹幕

### ISSUE THREAD

**Issue by lbcz-tian** [leiurayer/downkyi#203]
今天突然下不了弹幕了，设置了也开了但就是不下载，不知道为什么😢

**Comment by leiurayer** [comment]
所有的都下载不了弹幕吗，下载不了的链接贴出来吧

**Comment by lbcz-tian** [comment]
> 所有的都下载不了弹幕吗，下载不了的链接贴出来吧

只测试了哈利波特3和4，都没有下载弹幕，指环王可以下弹幕😢

**Comment by lbcz-tian** [comment]
哈利波特5也不行，估计哈利波特全系都下不了😢😢不知道为啥

**Comment by lbcz-tian** [comment]
> 所有的都下载不了弹幕吗，下载不了的链接贴出来吧

哈哈哈哈哈哈哈哈哈我知道为啥了，哈利波特太火了，弹幕有点多，转换用了太久所以我以为没下下来。我刚吃饭没关应用，回来一看，好家伙一个弹幕有7M，打开后有6w条🤣🤣🤣
