### ISSUE TITLE
是否考虑加入视频自定义命名规则

### ISSUE THREAD

**Issue by tgaochn** [leiurayer/downkyi#206]
感谢作者开发的工具, 请问是否考虑加入视频自定义命名规则?
别的软件有类似的功能我觉得非常方便, 批量下载的时候很容易归类整理.
![image](https://user-images.githubusercontent.com/22850831/151685945-fc193c4b-350b-432f-8a22-ef4934172d01.png)

**Comment by leiurayer** [comment]
参看 #201
