### ISSUE TITLE
Symantec reporting Torjan.Gen.9 with release 1.4.0

### ISSUE THREAD

**Issue by amsteel** [leiurayer/downkyi#214]
![image](https://user-images.githubusercontent.com/16197031/153522610-69b1352a-e162-408a-ab0b-17ec50b6a326.png)
![image](https://user-images.githubusercontent.com/16197031/153522696-7792c631-c81a-45eb-89bc-8e0b6ad9e404.png)

**Comment by leiurayer** [comment]
程序发布时进行了压缩，所以可能会误报。如果担心有病毒，可以放在虚拟机中运行
