### ISSUE TITLE
【您的软件疑似被淘宝店家倒卖】作者你好，我在淘宝看到有店家倒卖您的软件，请问店家是本人吗？

### ISSUE THREAD

**Issue by yuankeyuan** [leiurayer/downkyi#217]
链接：【淘宝】https://m.tb.cn/h.fmbazoS?tk=qL4s23R3uR4
「b站视频下载器哔哩哔哩bilibili视频素材批量下载工具mp4格式转换」
淘宝店家：五月软件
如果是作者本人那当然最好不过了。如果是倒卖狗，建议报警处理。实在看不惯人拿开源软件去倒卖

**Comment by yuankeyuan** [comment]
> 理解你能够的心情,售卖软件 不是开源 apache apache 协议允许分发分发
真是商业鬼才

**Comment by leiurayer** [comment]
虽然不能禁止别人销售，但是在软件中也有github仓库的链接，购买软件的人看见了自然会发现上当了
况且同类型软件大都可以免费使用，在淘宝上购买的人不能视为一般目标用户，随他去吧

当然我会在软件中适当增加提醒，告诉用户这是免费的、开源的

**Comment by JellyBlack** [comment]
商品详情页并没有标注GitHub链接，购买后发的文件极大概率不包含源码，这已违反GPL 3.0的第6条协议。
