### ISSUE TITLE
请问如何在本地构建应用?

### ISSUE THREAD

**Issue by aifreedom** [leiurayer/downkyi#220]
刚刚提交了一个PR (https://github.com/leiurayer/downkyi/pull/219), 但无法在本地验证是否成功修复了弹幕ASS文件的bug. 请问如何在本地构建应用?

**Comment by leiurayer** [comment]
拉取1.5.x分支，可以在本地编译

**Comment by leiurayer** [comment]
1.5.x中弹幕时间轴的bug已经修复
