### ISSUE TITLE
希望增加视频序号的功能

### ISSUE THREAD

**Issue by AAAleaf** [leiurayer/downkyi#228]
下载一个序列的视频，up主的视频没有序号，下载下来就是字母排序的，内容的顺序布置前后，看视频不知道哪个先哪个后，希望开发人员增加一个下载前添加序号的功能，感谢。

**Comment by leiurayer** [comment]
在设置里支持增加序号

**Comment by AAAleaf** [comment]
看到了，之前没注意那个小地方，谢谢
