### ISSUE TITLE
最新版个人主页会闪退，而且在主页中选中的下载也会闪退，闪退了会打不开。

### ISSUE THREAD

**Issue by 1963775891** [leiurayer/downkyi#234]

**Comment by conan4803** [comment]
在我电脑里直接打开就出错，先换回1.4.0

**Comment by leiurayer** [comment]
出现闪退的用户mid发一下吧

**Comment by leiurayer** [comment]
> 在我电脑里直接打开就出错，先换回1.4.0

打开就出错是直接崩溃呢还是弹窗？

**Comment by conan4803** [comment]
> > 在我电脑里直接打开就出错，先换回1.4.0
> 
> 打开就出错是直接崩溃呢还是弹窗？

您好， 有弹窗，如图所示
![Snipaste_2022-03-05_11-55-36](https://user-images.githubusercontent.com/3960732/156866793-e6baf472-1f00-42c1-99c4-d06c81b9c8ce.png)

**Comment by kytrun** [comment]
解决了，【运行兼容性疑难解答】
![image](https://user-images.githubusercontent.com/32519285/156908155-8d7ea111-ae85-498e-9aa0-b724d3a1482a.png)

**Comment by songtengfei95** [comment]
刚下载最新版，随便点击几下就闪退了

**Comment by wtywtykk** [comment]
@leiurayer 
找到一个会导致闪退的bug，性别如果填写了“保密”，会导致加载性别图标时候图标路径为空。然后new BitmapImage(sexUri)闪退
ViewMySpaceViewModel 529行
但这个似乎不会导致之后也打不开

**Comment by leiurayer** [comment]
> @leiurayer 找到一个会导致闪退的bug，性别如果填写了“保密”，会导致加载性别图标时候图标路径为空。然后new BitmapImage(sexUri)闪退 ViewMySpaceViewModel 529行 但这个似乎不会导致之后也打不开

感谢反馈，已修复
