### ISSUE TITLE
win11 21H2 22000.527下，运行diwnkyi 1.5.0易崩溃

### ISSUE THREAD

**Issue by zhattyt** [leiurayer/downkyi#236]
win11 21H2 22000.527下，运行diwnkyi 1.5.0易崩溃，昨晚还下了一会后直接打开就不出弹框了，我看着像是aria2启动了，程序也没有启动，重启都没办法启动，望查询机制，本机无杀毒，1.4.0能解析不能下载（已经删除了）。
![UQX$K`QEGIMIUK725SY7 5W](https://user-images.githubusercontent.com/32856463/156911044-0b468741-6ec0-41b1-a0e5-1ae80b1e2a59.png)

**Comment by verity886** [comment]
同样的问题，甚至删除文件再解压一遍也启动不了

**Comment by zhattyt** [comment]
补充，v1.5.0-alpha2依旧打不开，不知道是怎么了，后台显示是在运行的，要么打开就闪退了

![QQ截图20220307023415](https://user-images.githubusercontent.com/32856463/156937106-daf54960-68b3-4d42-b6d8-77c1d5121a85.png)
。
