### ISSUE TITLE
150A2 Win11 解析视频后点下载两秒闪退

### ISSUE THREAD

**Issue by STC214** [leiurayer/downkyi#238]
..

**Comment by STC214** [comment]
之后会有差不多几十秒的内存驻留exe

**Comment by leiurayer** [comment]
我没有win11的环境，等我装个虚拟机测试一下

**Comment by leiurayer** [comment]
虚拟机Win11下可以正常使用，应该是软件本身的问题。
闪退时解析的视频是什么？在哪个页面下操作的？弹出下载设置窗口了吗，或者点击下载后直接闪退？

**Comment by STC214** [comment]
> 虚拟机Win11下可以正常使用，应该是软件本身的问题。 闪退时解析的视频是什么？在哪个页面下操作的？弹出下载设置窗口了吗，或者点击下载后直接闪退？

任意视频都闪退 没有下载目录选择窗口
