### ISSUE TITLE
1.5.0-Alpha2崩溃

### ISSUE THREAD

**Issue by gagadsfg** [leiurayer/downkyi#240]
本人Win7 64位系统，运行此版本视频解析成功后点击下载后立即崩溃，之后再打开软件时就提示停止工作进不去。我就回退到了1.4.0
还望修复一下。

**Comment by leiurayer** [comment]
视频链接发一下

**Comment by xhtxzwj** [comment]
我的也是, 一直崩溃, 没成功下载一个视频

**Comment by gagadsfg** [comment]
> 视频链接发一下

[https://www.bilibili.com/bangumi/play/ss41346?t=93]
不付费可以解析6分钟试看，付费后可以在48小时内解析完整内容，之前1.4.0版本就没问题。
