### ISSUE TITLE
1.5.0 alpha2 如何配置实现下载某个UP主全部视频功能

### ISSUE THREAD

**Issue by honeyeyo** [leiurayer/downkyi#243]
测试使用的如下网址。
https://space.bilibili.com/316568752?spm_id_from=333.337.0.0
![image](https://user-images.githubusercontent.com/7601292/157241901-2a97aac0-a77e-4077-98c8-42e7ca867c54.png)
可以解析到所有视频。一共分成16页
![image](https://user-images.githubusercontent.com/7601292/157242012-e509004d-83cc-4b57-8ae7-71294f529bc0.png)
点击下载全部。
结果比较好的情况是可以下载当前页的30个视频。但是还有一定概率在没有完成下载的情况下闪退。

想了解一下如何实现一键下载16页的全部视频？非常感谢！

**Comment by leiurayer** [comment]
闪退的问题已经找到，下次更新修复；一键下载全部视频有概率失败，尤其在网络不稳定时，因此目前不能一键下载，只能分页
