### ISSUE TITLE
1.5.0-alpha2下载合集里单个视频时闪退

### ISSUE THREAD

**Issue by linoodb** [leiurayer/downkyi#245]
![image](https://user-images.githubusercontent.com/22164766/157529795-4a57138e-4ed5-4a8a-b842-826d81ece48c.png)
链接：https://www.bilibili.com/video/BV1VL4y1n7cY?spm_id_from=333.999.0.0
解析出来点下载选中项就闪退了win10系统

**Comment by botnang** [comment]
![Snipaste_2022-03-10_12-09-17](https://user-images.githubusercontent.com/32015065/157587215-5c1a28dd-8144-455b-b178-f7ae7aa01874.png)
同样的问题，点“下载选中项”按钮闪退。
也是win10 64位系统，无任何第三方杀毒/优化/美化软件。

**Comment by macl1012** [comment]
同样的问题，选择合集中的一个或者全部下载，程序闪退。
win10 64位。
![image](https://user-images.githubusercontent.com/25656800/157798766-93cb13e0-00d3-4d24-afcf-85be6e6edaa5.png)

视频链接：https://www.bilibili.com/video/BV1DF411e7FM/?spm_id_from=pageDriver
