### ISSUE TITLE
1.4.0与1.5.0-alpha2两版本 均提示无法下载音频

### ISSUE THREAD

**Issue by Varlalnub** [leiurayer/downkyi#249]
遂导致视频无法正常完成下载。

如图：
https://imgur.com/a/9lyyXhw

**Comment by leiurayer** [comment]
检查一下aria2是否在正常工作

**Comment by troublewind** [comment]
> 遂导致视频无法正常完成下载。
> 
> 如图： https://imgur.com/a/9lyyXhw

我这里也是同样的问题，哥们解决了吗，最新的alpha3也是一点就下载失败

**Comment by troublewind** [comment]
> 检查一下aria2是否在正常工作

我在win11的电脑上下载是有问题的，未登录账号下默认只能解析到720p，并且下载失败；
而另一台win10电脑上不用登录也能解析到1080p，并且成功下载；
观察目录下的aira.log发现了一些错误码，不知是否有帮助
----
  -> [AbstractCommand.cc:792] errorCode=19 CUID#11 - Name resolution for upos-sz-mirrorcosb.bilivideo.com failed:Could not contact DNS servers
2022-03-12 18:26:22.944200 [INFO] [AsyncNameResolverMan.cc:83] CUID#12 - Resolving hostname upos-sz-mirrorcos.bilivideo.com
2022-03-12 18:26:22.944200 [INFO] [HttpServer.cc:187] HTTP Server received request

**Comment by troublewind** [comment]
> 检查一下aria2是否在正常工作

在网上找到原因了，我装了vmware，会创建虚拟网卡，只要图中这个虚拟网卡是启用状态，必定会下载失败，这问题能够解决吗？
![image](https://user-images.githubusercontent.com/16570023/158029828-4e8f01db-27d2-4ece-acd3-424269b2a0cc.png)
另外，不登录账号无法解析1080p是正常的吗，没有找到原因。
![image](https://user-images.githubusercontent.com/16570023/158029916-5413d829-431c-4785-ac59-afe44453d19c.png)

**Comment by Varlalnub** [comment]
> > 遂导致视频无法正常完成下载。
> > 如图： https://imgur.com/a/9lyyXhw
> 
> 我这里也是同样的问题，哥们解决了吗，最新的alpha3也是，弹幕封面那些能下载，音频视频就下载失败

没有解决……你下方回复我也看了，而且巧的是我这边也有VM的虚拟网卡，按照你的建议，设置禁用了VMnet1，还是不行……

**Comment by troublewind** [comment]
> > > 遂导致视频无法正常完成下载。
> > > 如图： https://imgur.com/a/9lyyXhw
> > 
> > 
> > 我这里也是同样的问题，哥们解决了吗，最新的alpha3也是，弹幕封面那些能下载，音频视频就下载失败
> 
> 没有解决……你下方回复我也看了，而且巧的是我这边也有VM的虚拟网卡，按照你的建议，设置禁用了VMnet1，还是不行……

我觉得应该就是这个问题，你把除上网卡外其它的都禁了，重开downkyi试试，可以的话再逐一排查。
