### ISSUE TITLE
打开完下了一个视频就打不开了。

### ISSUE THREAD

**Issue by tangjiaq1** [leiurayer/downkyi#251]

**Comment by xingsuxingchen** [comment]
DownKyi-1.5.0-alpha3版本也崩溃了！只有启动界面logo一闪而过

**Comment by verity886** [comment]
alpha3同样闪退，删除目录重新解压问题依旧。请问是否在其他目录存有配置文件？

**Comment by gaohc001** [comment]
alpha3b一样的，下载了部分，然后闪退再打开一闪就又自动关闭了。求解决
