### ISSUE TITLE
提出一个不友善的设计，反映一下。

### ISSUE THREAD

**Issue by wwwvvv113** [leiurayer/downkyi#264]
![image](https://user-images.githubusercontent.com/33594561/158364097-5c52a9c8-0aff-4379-abb9-84ff6799549f.png)
现在最新的1.5 第四个修正版，每次只能在下载的时候选择下载什么内容，而且更改了下载内容后下一次下载也不保存上一次选择的内容，对于要一次下载多个视频时，或要重复操作很多次时，就导致每次都要选择下载什么内容（小弟只想下载视频，其他的不想下载。）能把这个下载设置整合到主界面设置UI里吗？或者其他能解决上述问题的也可以。提个小小建议，制作者勿怪。

**Comment by leiurayer** [comment]
5.0-alpha7已添加此功能
