### ISSUE TITLE
请问DownKyi-1.5.0-alpha4的页面为何不能调整大小

### ISSUE THREAD

**Issue by reno175677** [leiurayer/downkyi#266]
DownKyi-1.5.0-alpha4的页面无法调整大小，所以很多按键都被在电脑主页面外，使用很不方便，全屏时，整个底部按键都无法找到，希望修改

**Comment by lbcz-tian** [comment]
我的也是同样的问题，按键在屏幕外面😂

**Comment by leiurayer** [comment]
屏幕是多大的？

**Comment by reno175677** [comment]
> 屏幕是多大的？

抱歉，我是电脑白痴，我也不知道自己电脑是多大的，只知道 我的电脑是 联想 yoga slim 7.  看电影时全屏是1080p。

**Comment by lbcz-tian** [comment]
> 屏幕是多大的？

1080P，win11，150%缩放。换125缩放可以显示了

**Comment by reno175677** [comment]
> > 屏幕是多大的？
> 
> 1080P，win11，150%缩放。换125缩放可以显示了

谢谢告知，但还是希望正式版本中有个页面调大小功能。本来我电脑字就小，再调小看着更难受。

**Comment by leiurayer** [comment]
150%缩放已支持显示
