### ISSUE TITLE
是要下载其他辅助插件，还是直接下载解析就可以下载？目前我解析完下载一直无速度。https://ibb.co/1f5jrwT

### ISSUE THREAD

**Issue by B8715499** [leiurayer/downkyi#267]
https://ibb.co/1f5jrwT

**Comment by zfujie** [comment]
我起初跟你的情况一样，现在好了，但不知道是什么原因，可以从一下几方面入手：
1.杀毒软件，关掉试试。
2.防火墙，看看有没有拦截aria2c。
3.旧版文件，可能是冲突了。
4.虚拟机，装了虚拟机的，试试把虚拟机的网卡都禁了，重启系统，这里有人提过这点，我也这样操作了，但是我现在启用了虚拟机网卡也可以下载。

**Comment by B8715499** [comment]
> 1. 杀毒软件，关掉了。 2. 防火墙，看看有没有拦截aria2c 3. 旧版4. 虚拟机，装了虚拟机的，试试 把虚拟机的网卡都禁了，重启这个系统，这里有人现在提过点，我也这样操作了，但是我启用了虚拟机网卡也可以下载。

非常感谢！应该是防火墙的原因，改了一下可以下了。
