### ISSUE TITLE
v1.5.0-alpha6打开关闭后，弹出错误窗口，每次都这样

### ISSUE THREAD

**Issue by jzmswe** [leiurayer/downkyi#277]
OS Win7 CHS X64 旗舰。
以前的几个版本，打开关闭后都没这个窗口。
![2022-03-20_101849](https://user-images.githubusercontent.com/11971258/159145225-ba2c0f53-10ef-4eaf-afac-5a7b12d00abf.png)

**Comment by leiurayer** [comment]
试试v1.5.0-alpha7还有没有这个问题
