### ISSUE TITLE
希望最新的 1.5版本跟1.4版本一样，有解析后自动下载的功能！

### ISSUE THREAD

**Issue by jzjjzjok** [leiurayer/downkyi#281]
希望最新的 1.5版本跟1.4版本一样，有解析后自动下载的功能！  

因为有时候，一个页面解析，有很多很多的视频，需要时间长，不可能让人守着这么长的解析时间，再去点击下载。效率太低了。

**Comment by leiurayer** [comment]
v1.5.0-alpha7已添加此功能
