### ISSUE TITLE
视频混流卡住

### ISSUE THREAD

**Issue by jxyu1217** [leiurayer/downkyi#287]
我用DownKyi-1.5.0-alpha6版下载哔哩哔哩视频，一直卡在视频混流过不去，请问是什么原因？我试过3台win7的电脑，一台win10的电脑都是这种情况
![微信图片_20220323115946](https://user-images.githubusercontent.com/102202123/159621351-f206d9c4-1a5b-43c2-bae7-a3f4055aafae.png)
。

**Comment by renllem** [comment]
我也是

**Comment by leiurayer** [comment]
发一下相关日志

**Comment by jxyu1217** [comment]
这是之前卡住时的日志：[20220327(0).log](https://github.com/leiurayer/downkyi/files/8356756/20220327.0.log)
不过我换64位的操作系统就好了，64位win7和64位win10都可以。

**Comment by leiurayer** [comment]
> [20220327(0).log](https://github.com/leiurayer/downkyi/files/8356756/20220327.0.log) 不过我换64位的操作系统下载就没有问题。

在32位系统下会出现这个问题，64位正常使用，是吗？

**Comment by jxyu1217** [comment]
> > [20220327(0).log](https://github.com/leiurayer/downkyi/files/8356756/20220327.0.log) 不过我换64位的操作系统下载就没有问题。
> 
> 在32位系统下会出现这个问题，64位正常使用，是吗？

是的
