### ISSUE TITLE
Win10自动删除downkyi

### ISSUE THREAD

**Issue by Moceee** [leiurayer/downkyi#288]
我的Win10会把downkyi归类成威胁然后自动删除，前几天还能用，今天就用不了了。重新下载很多次了。请问有什么解决方法吗？

**Comment by jzjjzjok** [comment]
https://www.baidu.com/s?word=Win10%E8%87%AA%E5%8A%A8%E5%88%A0%E9%99%A4downkyi&tn=94819464_hao_pg

**Comment by jzjjzjok** [comment]
https://jingyan.baidu.com/article/0aa2237518891f88cc0d64ef.html

**Comment by jzjjzjok** [comment]
http://www.xitongcheng.com/jiaocheng/win10_article_63286.html

**Comment by Moceee** [comment]
感谢这位兄弟，问题解决了
