### ISSUE TITLE
去水印如何设置参数；总是报错：No such filter: 'delogo'

### ISSUE THREAD

**Issue by heonho** [leiurayer/downkyi#289]
我水印尺寸与位置设置为：
宽：1254；高：66；X：1254；Y：66

报错信息如下：
`Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\BV素材\素材\“这TM才叫颜值天花板！”\1-“这TM才叫颜值天花板！”-1080P 高清-HEVC.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2mp41
    encoder         : Lavf59.16.100
    description     : Packed by Bilibili XCoder v2.0.2
  Duration: 00:01:33.88, start: 0.000000, bitrate: 946 kb/s
  Stream #0:0[0x1](und): Video: hevc (Main) (hev1 / 0x31766568), yuv420p(tv, bt709), 1080x1920, 808 kb/s, 30 fps, 30 tbr, 16k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> mpeg4 (native))
  Stream #0:1 -> #0:1 (aac (native) -> aac (native))
Press [q] to stop, [?] for help
[AVFilterGraph @ 00000171ddf007c0] No such filter: 'delogo'
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
[aac @ 00000171d6777400] Qavg: 26086.232
[aac @ 00000171d6777400] 2 frames left in the queue on closing
Conversion failed!`

是我的水印设置有错误，还是这个无法过滤: 'delogo'？
请问该如何设置水印尺寸与位置？

**Comment by heonho** [comment]
![Quicker_20220324_164926](https://user-images.githubusercontent.com/67063136/159878147-66e08845-21f8-4614-b8c5-f0883d8fcd5e.png)

**Comment by patricksun2807** [comment]
> 尝试将FFmpeg.exe用以下链接中的程序更换： [ffmpeg-n5.0-latest-win64-gpl-5.0.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.0-latest-win64-gpl-5.0.zip)

有没有定位水印宽高的软件，小白也可以用的

**Comment by patricksun2807** [comment]
> 尝试将FFmpeg.exe用以下链接中的程序更换： [ffmpeg-n5.0-latest-win64-gpl-5.0.zip](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n5.0-latest-win64-gpl-5.0.zip)

强烈建议尽快加入一个自动检测水印宽高的功能
