### ISSUE TITLE
【v1.5.0-alpha7版本】 下载内容选择取消勾选弹幕、封面下载不起作用

### ISSUE THREAD

**Issue by Kele0113** [leiurayer/downkyi#292]
v1.5.0-alpha7版本 取消勾选弹幕、封面下载不起作用，仍然会把封面字幕弹幕全下载

**Comment by leiurayer** [comment]
是否设置了默认下载目录？

**Comment by Kele0113** [comment]
> 是否设置了默认下载目录？
作者你好，新版确实比A7版好用了，谢谢你，我能否再提点小意见
1.收藏跟稍后再看这两个栏目里面的下载全部按钮有点猛，加一个二次提醒最好了
2.还是这两栏目，点击视频之后才出现勾选框而且我取消勾选不了，我觉得写成直接显示的勾选框比较好操作
