### ISSUE TITLE
请问为什么打开exe后cmd闪出就没反映了？  我已经安装.Net了

### ISSUE THREAD

**Issue by xianweibo** [leiurayer/downkyi#319]
请问为什么打开exe后cmd闪出就没反映了？  我已经安装.Net了
操作系统是win10

**Comment by leiurayer** [comment]
运行downkyi.exe程序

**Comment by L9fa** [comment]
..下载的压缩包里解压开之后没有downkyi.exe程序..是什么原因

**Comment by yuhan2680** [comment]
> 运行downkyi.exe程序

下载下来没看到downkyi.exe呀

**Comment by JellyBlack** [comment]
> > 运行downkyi.exe程序
> 
> 下载下来没看到downkyi.exe呀

请确认你下载的是Release里的发行版，而不是源码

**Comment by yuhan2680** [comment]
> > > 运行downkyi.exe程序
> > 
> > 
> > 下载下来没看到downkyi.exe呀
> 
> 请确认你下载的是Release里的发行版，而不是源码

Release里的发行版是在哪下

**Comment by leiurayer** [comment]
https://github.com/leiurayer/downkyi/releases/latest
