### ISSUE TITLE
建议：加入 合集和列表 方便快速选择下载，提高操作效率。

### ISSUE THREAD

**Issue by sjh024** [leiurayer/downkyi#323]
如题。

**Comment by jzjjzjok** [comment]
大力支持！ B站 一个页面最多只显示３０个视频，假如 UP 主的里面有５００个视频，则需要分开 １７个页面显示 ，象我等如饥似渴地吸取知识营养的人来说，下载这些视频则要点击１７次页面，每打开一次页面，则需要再点击下载软件中的 ”全部下载“按钮！ 多点击 １７＋１７＝３４次按钮，多点击还是次要的，问题是要等这个页面下载完后，才能点击下一个页面，需要人守着看上一个页面下载完了没有！ 有时候来看一下，可能上一个页面还没有下完，有时候可能是早已经下完，都不能高效下载。 用  python 的爬行功能，应该能够自动翻页面探索 UP 主里的所有视频的吧？

**Comment by jzjjzjok** [comment]
大力支持！ B站 一个页面最多只显示３０个视频，假如 UP 主的里面有2000个小视频，则需要分开 67个页面显示 ，象我等如饥似渴地吸取知识营养的人来说，下载这些视频则要点击67次页面，每打开一次页面，则还需要再点击下载软件中的 ”全部下载“按钮！ 多点击 67＋67＝134 次按钮，多次点击还是次要的，问题是要等这个页面下载完后，才能点击下一个页面，需要人守着察看上一个页面下载完了没有！ 有时候来看一下，可能上一个页面还没有下完，有时候可能是早已经下完，都浪费时间与精力。 用  python 的爬行功能，应该能够自动翻页，探索 UP 主里的所有视频的吧？   比如这个页面： 
https://space.bilibili.com/456305479/video
