### ISSUE TITLE
建议增加下载字幕的功能

### ISSUE THREAD

**Issue by Tonyzhang007** [leiurayer/downkyi#335]
建议增加下载字幕的功能

**Comment by jzjjzjok** [comment]
设置里不是有选择的么？   我还想不要封面与字幕，而只要视频呢！！！   可是，却硬要把封面与字幕都下了，占用了硬盘位置。

**Comment by Tonyzhang007** [comment]
> 设置里不是有选择的么？ 我还想不要封面与字幕，而只要视频呢！！！ 可是，却硬要把封面与字幕都下了，占用了硬盘位置。

设置里的选项是弹幕而不是字幕吧，不一样啊
