### ISSUE TITLE
建议 1.5 恢复 将所有视频下载到同一个目录 （【为不同视频分别创建文件夹】选项）

### ISSUE THREAD

**Issue by lesca** [leiurayer/downkyi#339]
1.4版本中【为不同视频分别创建文件夹】的选项在1.5版本中没有了，取消勾选后可以将所有视频下载到同一个目录下，这在1.5版本中没有了。希望能恢复将所有视频下载到一个文件夹下。

**Comment by Qixingchen** [comment]
1.5 不是可以自定义文件名了么 斜杠 / 就是用来建文件夹的

**Comment by lesca** [comment]
我收回这个问题 使用 “/” 就是建立文件夹的意思 修改文件规则就好了 研究中！
得承认1.5 比1.4 牛多了！！
