### ISSUE TITLE
解析下载失败

### ISSUE THREAD

**Issue by mh89783** [leiurayer/downkyi#344]
今晚用此软件下载时一直提示下载失败，不知是什么原因

**Comment by leiurayer** [comment]
看看日志文件

**Comment by jzjjzjok** [comment]
这几个小时，我的也是很难下载！ 之前下载失败的时候，我用鼠标自动点击器高速自动点击“全部开始”，总有可能 下载来，但是这几个小时，无论怎么点击，都下载不了，几小时后又好 了，估计 哔哩哔哩网站当时正在维护

**Comment by mh89783** [comment]
> 看看日志文件

这方面不是太了解，不过目前已经恢复下载了
