### ISSUE TITLE
在这里下载压缩包时速度越来越慢低至40KB/s，最后速度直接归零下载失败，下载其他压缩包都正常网速跑满下载的，这是为什么

### ISSUE THREAD

**Issue by xiaociwei1994** [leiurayer/downkyi#346]
下载dpwnkyi-1.5.0时，下载到一半就停止下载了

**Comment by leiurayer** [comment]
防火墙的问题，github有时候需要科学上网，如果已经有一个旧版本的程序了，可以通过“关于”里的检查更新来下载最新版程序

**Comment by xiaociwei1994** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复.

**Comment by xiaociwei1994** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复.
