### ISSUE TITLE
发现一个BUG，下载的弹幕文件.ass，如果视频超过1小时，字幕时间错误

### ISSUE THREAD

**Issue by cheng-lix** [leiurayer/downkyi#353]
可能平时只看短视频，测试时没有发现这个问题。下面是某个字幕中文本：

Dialogue: -1,0:59:54.06,1:60:10.06,Danmaku,,0000,0000,0000,,{\move(2256, 24, -336, 24)\c&H722E00\3c&H000000}神授塔什么时候去
Dialogue: -1,1:60:09.01,1:60:22.01,Danmaku,,0000,0000,0000,,{\move(2064, 24, -144, 24)\3c&H000000}进度条“危”

第一行字幕时间： 0:59:54.06  -> 1:60:10.06
第二行字幕时间： 1:60:09.01  -> 1:60:22.01
可以看到，时间超过1小时， 小时位已经为1， 分钟位没有重新从0开始，而是继续在增加，已经超过60，这是明显的错误。
实测看视频时，加载ass字幕，超过1小时后，字幕就显示不出来了。
正确的应该是：
第一行字幕时间： 0:59:54.06  -> 1:00:10.06
第二行字幕时间： 1:00:09.01  -> 1:00:22.01

**Comment by leiurayer** [comment]
用的哪个版本？

**Comment by cheng-lix** [comment]
1.50版，又测试了几个短的视频，什么弹幕都不能下载了，只要下弹幕，下载就卡在这里，无法完成了。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: Li Cheng ***@***.***>
发送时间: Monday, April 25, 2022 12:58:26 PM
收件人: leiurayer/downkyi ***@***.***>; leiurayer/downkyi ***@***.***>
抄送: Author ***@***.***>
主题: 回复: [leiurayer/downkyi] 发现一个BUG，下载的弹幕文件.ass，如果视频超过1小时，字幕时间错误 (Issue #353)




用的1.40版。

1.50版刚才测了下， 但是字幕下不来，程序卡住不动了，已经10多分钟了。



***@***.***



从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送



发件人: ***@***.***>
发送时间: 2022年4月25日 12:34
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [leiurayer/downkyi] 发现一个BUG，下载的弹幕文件.ass，如果视频超过1小时，字幕时间错误 (Issue #353)



用的哪个版本？

―

**Comment by jzjjzjok** [comment]
为啥你们喜欢要弹幕？  我一直想去掉弹幕，总去掉不了呢！ 总是会下载来。

**Comment by leiurayer** [comment]
![image](https://user-images.githubusercontent.com/19290097/166489380-aee805ee-e43c-4133-a592-1dfb7f049f7b.png)

电影《让子弹飞》1小时处的弹幕，没有发现问题。
https://www.bilibili.com/bangumi/play/ss12548

**Comment by cheng-lix** [comment]
我下1.5 最新的Alpha6版本，没问题了。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: leiurayer ***@***.***>
发送时间: Tuesday, May 3, 2022 11:57:12 PM
收件人: leiurayer/downkyi ***@***.***>
抄送: cheng-lix ***@***.***>; Author ***@***.***>
主题: Re: [leiurayer/downkyi] 发现一个BUG，下载的弹幕文件.ass，如果视频超过1小时，字幕时间错误 (Issue #353)


[image]<https://user-images.githubusercontent.com/19290097/166489380-aee805ee-e43c-4133-a592-1dfb7f049f7b.png>

电影《让子弹飞》1小时处的弹幕，没有发现问题。
https://www.bilibili.com/bangumi/play/ss12548

―

**Comment by cheng-lix** [comment]
用的1.40版。
1.50版刚才测了下， 但是字幕下不来，程序卡住不动了，已经10多分钟了。

***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年4月25日 12:34
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [leiurayer/downkyi] 发现一个BUG，下载的弹幕文件.ass，如果视频超过1小时，字幕时间错误 (Issue #353)


用的哪个版本？

―
