### ISSUE TITLE
下载后一直混流中

### ISSUE THREAD

**Issue by kuluwu** [leiurayer/downkyi#356]
看了下日志大概是这里
2022/4/26 23:00:19   [14]   ERROR   StorageUtils  值不能为 null。
参数名: address
   在 System.Net.WebClient.DownloadFile(String address, String fileName)
   在 DownKyi.Core.Storage.StorageUtils.DownloadImage(String url, String localFile)

**Comment by leiurayer** [comment]
操作系统是32位还是64位？

**Comment by kuluwu** [comment]
是32位的

**Comment by leiurayer** [comment]
附带的ffmpeg.exe是64位的，在32位系统中无法运行，所以会卡在混流中

**Comment by kuluwu** [comment]
确实是这样,感谢,已解决问题
