### ISSUE TITLE
查毒软件报毒

### ISSUE THREAD

**Issue by DILIRee** [leiurayer/downkyi#358]
请检查软件是否被恶意种毒，谢谢

**Comment by bluesky2030** [comment]
360报毒

**Comment by oloopy** [comment]
Windows Defender提示病毒：Trojan:Script/Oneeva.A!ml

**Comment by peakandyuri** [comment]
zip文件报毒，解压出来的文件没有报毒

**Comment by kebugcheckex** [comment]
我的Windows Defender提示的是 Trojan:Win32/Mamson.A!ml
