### ISSUE TITLE
Virustotal查毒网站报毒

### ISSUE THREAD

**Issue by pigmanms** [leiurayer/downkyi#377]
我这个人， 下载什么都要查一下毒。
结果今天刚下完软件之后查毒，62个查毒软件其中9个说有毒。。。
请问你们有的时候也查出毒吗？

网址下方：
https://www.virustotal.com/gui/file/4fc6a36d0432e0d2e2ee930cbd995b5b905b44af6db6b2c9b416cba521d8f9fc

**Comment by pigmanms** [comment]
当然我不是不信任这个软件，只是问问。

**Comment by sakurayun** [comment]
看了一下分析记录，是误报

**Comment by pigmanms** [comment]
感谢回答
