### ISSUE TITLE
我现在是这样的，，，，不知道是什么原因应该是我的电脑的问题，但是不知道是什么问题net4.8也装了的

### ISSUE THREAD

**Issue by aassz3** [leiurayer/downkyi#390]
![image](https://user-images.githubusercontent.com/31858438/168024865-7d3c713d-bdc3-487d-b21e-554f2e1ea20d.png)

**Comment by leiurayer** [comment]
点击下方的解析按钮，或者在选中项鼠标右键单击，弹出菜单选择解析

**Comment by aassz3** [comment]
> 分类列表的解析点击点击或弹出菜单选择解析

谢谢已解决
