### ISSUE TITLE
分p视频部分无法下载

### ISSUE THREAD

**Issue by chilan666** [leiurayer/downkyi#393]
https://www.bilibili.com/video/BV1Dq4y1D7cr?spm_id_from=333.337.search-card.all.click     3P只能在音质为64K时下载，其他音质则下载失败

**Comment by ijrou** [comment]
1.5.2似乎已经修复了

**Comment by chilan666** [comment]
好的，已收到1.5.2更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "leiurayer/downkyi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月14日(星期六) 晚上11:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [leiurayer/downkyi] 分p视频部分无法下载 (Issue #393)





 
1.5.2似乎已经修复了

**Comment by ijrou** [comment]
> 好的，已收到1.5.2更新
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "leiurayer/downkyi" ***@***.***&gt;; 发送时间:&nbsp;2022年5月14日(星期六) 晚上11:06 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [leiurayer/downkyi] 分p视频部分无法下载 (Issue #393) 1.5.2似乎已经修复了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

测试发现还是存在问题，此版本并未修复
