### ISSUE TITLE
1.5.3功能缺失

### ISSUE THREAD

**Issue by pgy0809** [leiurayer/downkyi#446]
在更新1.5.3后，我发现“为每一个视频单独创建文件夹”这个选项消失了，不知道是因为因为BUG在修复而暂时停用还是编译意外，希望在1.5.4重新添加该选项

**Comment by Qixingchen** [comment]
自定义文件名中加个 / 就是建文件夹了
#339

**Comment by pgy0809** [comment]
是在文件名的前面还是后面呢？

**Comment by Qixingchen** [comment]
设置为 a / b 即 a是文件夹名 b是文件名

**Comment by pgy0809** [comment]
好的谢谢
