### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by A-little-bit-of-data** [leiurayer/downkyi#449]
下载的最新版1.5.3，电脑系统是Windows10
您好，请问这种怎么搞？
![image](https://user-images.githubusercontent.com/31812278/173755096-f38b060f-5a46-4aee-9a97-da555d3ab795.png)

**Comment by jzjjzjok** [comment]
1.    下载的是压缩文件，需要解压后运行。在解压软件么？ 
2.    有可能可执行文件被杀毒软件误杀，导致可执行文件无法正常运行。
![搜狗截图22年06月15日1642_1](https://user-images.githubusercontent.com/101977335/173784066-6d1af455-c9ea-4da3-8744-710fce8026f4.jpg)

**Comment by A-little-bit-of-data** [comment]
> 1. 下载的是压缩文件，需要解压后运行。在解压软件么？
> 2. 有可能可执行文件被杀毒软件误杀，导致可执行文件无法正常运行。
>    ![搜狗截图22年06月15日1642_1](https://user-images.githubusercontent.com/101977335/173784066-6d1af455-c9ea-4da3-8744-710fce8026f4.jpg)

解压出来了，和你下载的是一样的文件，因为是公司电脑，没权限加白名单，估计是被误删了吧
