### ISSUE TITLE
为什么现在无法抓取杜比全景声了？

### ISSUE THREAD

**Issue by RTGTX7** [leiurayer/downkyi#453]
为什么现在无法抓取杜比全景声？发现了个问题视频是只要有支持杜比视界才能支持杜比全景声抓取。可有些视频至支持杜比全景声不支持杜比视界。望修复

https://www.bilibili.com/video/BV1cY41177SS?spm_id_from=333.999.0.0&vd_source=4f9c13234a156dbc9f97a0367fb6d399

![image](https://user-images.githubusercontent.com/59045163/174464264-3ef9abfa-8c2b-4ba5-a013-389c430dc458.png)

**Comment by leiurayer** [comment]
已支持杜比全景声
7deee50
