### ISSUE TITLE
更新等于退步

### ISSUE THREAD

**Issue by patricksun2807** [leiurayer/downkyi#454]
自三月之后，软件一直在更新，但是却越来越难用，各种问题层出不穷，用户体验越来越差，这样下去还更新干嘛了，干脆断更算了

**Comment by ug802** [comment]
楼主非蠢即坏！人家免费给你用，你有问题可以提BUG，没必要这样说话！

**Comment by jjy7pspsjl** [comment]
支持2楼

**Comment by Honglong22** [comment]
免费的东西用惯了，居然敢开始喷了，真是惯得，真没牛逼给作者钱让他给你定制呀

**Comment by ug802** [comment]
这个人出言不逊好几次了。

**Comment by dreAmInGnu** [comment]
免费给你白嫖的不好好说话，你这种做法就是互联网的“搅屎棍”，人家好好的免费开发，要是被你这些一个两个的老鼠屎言行弄得断更，大家都没得用

**Comment by leiurayer** [comment]
这个项目只是为大家下载B站视频提供一种渠道，同类软件有很多，你觉得哪个好用、哪个适合就用哪个。开源软件就是这样，我只是用业余时间来开发，开发进度不会很快，也不可能让每个人都满意，如果你想要新功能但是目前还没有，可以pull request，或者你希望提供完善的服务，可以签订技术服务合同，那我可以全职为您服务。
