### ISSUE TITLE
无法在列表中手动选中多个视频

### ISSUE THREAD

**Issue by miaomimao** [leiurayer/downkyi#467]
奇怪的bug
试图用鼠标在列表中选择若干视频下载，
发现每次只能保持一个视频选中，选中第一个后再选第二个的时候第一个就自动被unselect了。
全选按钮可用与全选和清除全选。
win10

**Comment by leiurayer** [comment]
多选按住ctrl，连续多选按shift

**Comment by miaomimao** [comment]
> 多选按住ctrl，连续多选按shift

O(∩_∩)O谢谢搞定了，最好加个文字提示，这种选择方式太非主流
