### ISSUE TITLE
最近没法下载了，好像是小破站做防盗链了，下载总是失败

### ISSUE THREAD

**Issue by shijianzugouniai** [leiurayer/downkyi#484]
最近下载视频好慢，并且很容易出现下载失败的标志

**Comment by Sknact** [comment]
我今天下载没有成功过，1.5.2

**Comment by shijianzugouniai** [comment]
> 我今天下载没有成功过，1.5.2

1.5.3  试试

**Comment by Eyaaaaaa** [comment]
> 我發現原因了,去設置將 「Aria2 下載器」改成「內建下載器」就正常了, 至於為何會出現這個問題我就不清楚了.
> 
> 缺點就是下載時有時候會在最後的部份卡住,只能中斷再重新下載就能正常下載.

这个设置在什么地方啊。我没看到这个设置呀
