### ISSUE TITLE
你好，关于【未知设备】的情况怎么处理

### ISSUE THREAD

**Issue by ToneySun** [leiurayer/downkyi#496]
在上对B站的网站进行扫描的时候，是可以正常显示设备的，设备名称为Chrome。包括您的DownKyi
![image](https://user-images.githubusercontent.com/18101168/184520387-f10e4572-3871-4fae-b17b-2056a39fde64.png)

如果我在自己写的爬虫进行登录的话，会显示[未知设备]
![image](https://user-images.githubusercontent.com/18101168/184520400-74305fd5-d557-456e-82aa-7b0f6c919755.png)

我仔细查看了您在 [您的LoginQR.cs](https://github1s.com/leiurayer/downkyi/blob/HEAD/src/DownKyi.Core/BiliApi/Login/LoginQR.cs) 中的实现的代码片段，但是几乎是一致的（UA、Reference）。

我不理解为何您的应用可以是以“Chrome登录显示”，而我的应用 仅显示“未知设备”~呜呜呜

**Comment by leiurayer** [comment]
设置请求头user-agent
