### ISSUE TITLE
大佬好，我这里下载时停留在“视频混流中”很久不动，怎么办？

### ISSUE THREAD

**Issue by Warmtea555** [leiurayer/downkyi#499]
![1](https://user-images.githubusercontent.com/111330318/184789295-6c77c3d3-9244-41be-bc49-484ba99e28e3.jpg)

**Comment by leiurayer** [comment]
卡在视频混流中，检查ffmpeg.exe是否正常工作

**Comment by Warmtea555** [comment]
> 

谢谢大佬了，已经解决。问题好像是ffmpeg.exe被其他软件删除了，所以找了好久，重新下载了。

**Comment by kimojar** [comment]
我遇到这个问题是“以管理员身份运行”解决的。
