### ISSUE TITLE
用于解决无法识别新的分享链接

### ISSUE THREAD

**Issue by 897601689** [leiurayer/downkyi#506]
private void EnterBili()
        {
            if (InputText == null || InputText == string.Empty)
            {
                return;
            }

            LogManager.Debug(Tag, $"InputText: {InputText}");
            InputText = Regex.Replace(InputText, @"[【]*[^【]*[^】]*[】 ]", "");
            SearchService searchService = new SearchService();
            bool isSupport = searchService.BiliInput(InputText, Tag, eventAggregator);
            if (!isSupport)
            {
                // 关键词搜索
                searchService.SearchKey(InputText, Tag, eventAggregator);
            }

            InputText = string.Empty;
        }

**Comment by leiurayer** [comment]
已合并
