### ISSUE TITLE
请问你的实现原理是后台做了免登陆操作吗？

### ISSUE THREAD

**Issue by cq0702** [leiurayer/downkyi#522]
大佬好，最近研究播放b站高清视频，发现b站视频在不登录b站的情况下是没办法播放720及以上的分辨率视频的，最高480p,但是你的工具就可以直接下载高清，请问下你的实现原理是后台做了模拟登录绕过去了吗，还是纯前端可以做到，望告知下方向，感谢。

**Comment by leiurayer** [comment]
没有做任何操作，就是B站的api，请求时设置好request header 就行

**Comment by cq0702** [comment]
b站的api没有官网文档吧，是自己抓取总结的吗？如果有官方api文档可以发一下吗，如果是自己抓的，请问下获取未登录下的高清视频api是什么啊？望指导下，感谢。

**Comment by cq0702** [comment]
我大概了解了你的原理,下载完视频字段和音频片段后再通过FFmpeg进行合并，想问下这种可以实现边下载边播放吗？还是下载完合并后才能播放。我需求是想做到在自己的网页上在未登录b站情况下播放高清视频。

**Comment by leiurayer** [comment]
我用的api支持边下边播；
用浏览器的开发者工具很容易抓取到B站api，这个仓库系统性地记录了大部分api，用之前最好自己验证一下，B站修改api很频繁
https://github.com/SocialSisterYi/bilibili-API-collect
