### ISSUE TITLE
更新了1.5.4但视频解析出来没有hi-res，只解析出192

### ISSUE THREAD

**Issue by SongyaCAT** [leiurayer/downkyi#543]
![image](https://user-images.githubusercontent.com/57287191/197355327-fcfbb2e2-875d-4783-8a24-b04b93219a80.png)

https://www.bilibili.com/video/BV1ze411571w/

**Comment by leiurayer** [comment]
![image](https://user-images.githubusercontent.com/19290097/197371116-9c185024-2da5-49e3-bf1f-bed568dd7251.png)

检查一下设置的优先下载音质

**Comment by SongyaCAT** [comment]
![image](https://user-images.githubusercontent.com/57287191/197371583-9ad10453-89bd-42c2-913e-1524a76e0daa.png)
![image](https://user-images.githubusercontent.com/57287191/197371605-185dccd0-c58f-40ee-85be-efca35fbdab2.png)

已经设置了但还是不行，刚刚重新解压安装了一遍也是这样

**Comment by SongyaCAT** [comment]
好吧，破案了，是我放的D盘Program Files又被windows改权限了，换了个地方放程序就可以了
