### ISSUE TITLE
1.5.4 和 1.5.5 部分视频不能解析

### ISSUE THREAD

**Issue by tgaochn** [leiurayer/downkyi#554]
这个视频不能成功解析
https://www.bilibili.com/video/BV15G4y1873U/

**Comment by tgaochn** [comment]
1.5.3 版本解析没问题

**Comment by lrs95** [comment]
> 这个视频不能成功解析 https://www.bilibili.com/video/BV15G4y1873U/

我这1.5.4正常啊
![image](https://user-images.githubusercontent.com/24587454/201137531-cc1eb756-1b16-455e-83fb-ae376d2a76fd.png)

**Comment by lrs95** [comment]
1.5.5我试了也是正常的，检查下本地网络吧，是不是代理影响了
