### ISSUE TITLE
从1.5.1更新至1.5.5发现ass字幕文件无内容 

### ISSUE THREAD

**Issue by akaneJun** [leiurayer/downkyi#563]
昨天更新了1.5.5  发现下载完后发现ass字幕皆为1Kb文件，用txt打开后内容如下：    看的没人说这问题，不知道是不是自己问题，
[Script Info]
; Script generated by Downkyi Danmaku Converter
; https://github.com/FlySelfLog/downkyi
Title: EP01 20111002 0单选拔 UNGIRLS
ScriptType: v4.00+
Collisions: Normal
PlayResX: 1920
PlayResY: 1080
Timer: 10.0000
WrapStyle: 2
ScaledBorderAndShadow: no

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,黑体,54,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0.00,0.00,1,2.00,0.00,2,30,30,120,0
Style: Alternate,黑体,36,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0.00,0.00,1,2.00,0.00,2,30,30,84,0
Style: Danmaku,黑体,50,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0.00,0.00,1,1.00,0.00,2,30,30,30,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text

用别方式下载的ass文件：
[Script Info]
ScriptType: v4.00+
Collisions: Normal
PlayResX: 1920
PlayResY: 1080

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: AcplayDefault, Microsoft YaHei, 64, &H00FFFFFF, &H00FFFFFF, &H00000000, &H00000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 1, 0, 2, 20, 20, 20, 0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 3,0:00:00.00,0:00:04.00,AcplayDefault,,0000,0000,0000,,{\a6\pos(960, 1)\c&HEAA000\3c&HFFFFFF}山气日夕佳      "飛鳥"相与还！
Dialogue: 3,0:00:00.00,0:00:04.00,AcplayDefault,,0000,0000,0000,,{\a6\pos(960, 65)\c&H02F1FE\3c&HFFFFFF}夢開始的地方！！！
Dialogue: 3,0:00:00.00,0:00:04.00,AcplayDefault,,0000,0000,0000,,{\a6\pos(960, 129)\c&H7302CC\3c&HFFFFFF}梦开始的地方！！！
Dialogue: 3,0:00:00.00,0:00:04.00,AcplayDefault,,0000,0000,0000,,{\a6\pos(960, 193)\c&H1200E7\3c&HFFFFFF}白桥七花鸟！！！
Dialogue: 3,0:00:00.00,0:00:04.00,AcplayDefault,,0000,0000,0000,,{\a6\pos(960, 257)}进来就出不去了！

**Comment by akaneJun** [comment]
试了下1.5.4弹幕没问题

**Comment by yytssln** [comment]
现在支持下载中文字幕吗

**Comment by hoviron** [comment]
同样的问题 1.5.5弹幕全部没有什么内容，像是开了”硬核弹幕“

**Comment by vic233333** [comment]
同样的问题，应该是个bug。

**Comment by HayashiKaori** [comment]
同样的问题
