### ISSUE TITLE
1.5.5 弹幕文件无法下载

### ISSUE THREAD

**Issue by HayashiKaori** [leiurayer/downkyi#588]
只保存了个文件头：
[Script Info]
; Script generated by Downkyi Danmaku Converter
; https://github.com/FlySelfLog/downkyi
Title: “朋友越损，快乐越多”
ScriptType: v4.00+
Collisions: Normal
PlayResX: 1920
PlayResY: 1080
Timer: 10.0000
WrapStyle: 2
ScaledBorderAndShadow: no

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,黑体,54,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0.00,0.00,1,2.00,0.00,2,30,30,120,0
Style: Alternate,黑体,36,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0.00,0.00,1,2.00,0.00,2,30,30,84,0
Style: Danmaku,黑体,50,&H00FFFFFF,&H00FFFFFF,&H00000000,&H00000000,0,0,0,0,100,100,0.00,0.00,1,1.00,0.00,2,30,30,30,0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text

**Comment by HayashiKaori** [comment]
如图：

![图片](https://user-images.githubusercontent.com/57685624/204227554-c0fe2f6d-7a0d-484f-95af-7641a9282b4b.png)

**Comment by xflcx1991** [comment]
+1

**Comment by YaoYouGuan** [comment]
下载之后的ass弹幕文件很小，不到1KB，potplayer无法加载这个弹幕。
正常的弹幕文件有4M，potplayer可以加载弹幕文件。

**Comment by HayashiKaori** [comment]
> 下载之后的ass弹幕文件很小，不到1KB，potplayer无法加载这个弹幕。 正常的弹幕文件有4M，potplayer可以加载弹幕文件。

@YaoYouGuan 用回上个版本v1.5.4即可

**Comment by YaoYouGuan** [comment]
> > 下载之后的ass弹幕文件很小，不到1KB，potplayer无法加载这个弹幕。 正常的弹幕文件有4M，potplayer可以加载弹幕文件。
> 
> @YaoYouGuan 用回上个版本v1.5.4即可

okok

**Comment by leiurayer** [comment]
1.5.5缺少了System.Memory.dll文件，复制到程序根目录就可以了

**Comment by xflcx1991** [comment]
> 1.5.5缺少了System.Memory.dll文件，复制到程序根目录就可以了

那 System.Memory.dll 这个文件在哪里呢？

**Comment by xflcx1991** [comment]
> > 1.5.5缺少了System.Memory.dll文件，复制到程序根目录就可以了
> 
> 那 System.Memory.dll 这个文件在哪里呢？

好了，1.5.6 可以下载字幕了
