### ISSUE TITLE
关于DownKyi的本体优化建议

### ISSUE THREAD

**Issue by Dreamarix-Maritix-Xlous** [leiurayer/downkyi#605]
近日我痴迷在备份UP主的视频中，但是因为视频体积巨大（20Min/单视频），以至于我不得不选择AV1视频编码策略的视频，但是要一个个点...........能不能设置默认的解析视频编码呢？

**Comment by szbiao218** [comment]
有没有可能设置里有这个功能呢

**Comment by Dreamarix-Maritix-Xlous** [comment]
啊哈哈哈......我忘了


来自 MEIZU 18X

-------- 原始邮件 --------
发件人：szbiao218 ***@***.***>
时间：2023年1月6日 15:25
收件人：leiurayer/downkyi ***@***.***>
抄送：Dreamarix-Maritix-Xlous ***@***.***>,Author ***@***.***>
主题：Re: [leiurayer/downkyi] 关于DownKyi的本体优化建议 (Issue #605)
