### ISSUE TITLE
在点击自己头像后点击稍后再看里点击全部下载仍然会闪退。此BUG1.55已经存在，1.54没有。

### ISSUE THREAD

**Issue by 575610871** [leiurayer/downkyi#618]
在点击自己头像后点击稍后再看里点击全部下载仍然会闪退。此BUG1.55已经存在，1.54没有。

**Comment by leiurayer** [comment]
1.5.7应该没有这个问题了，更新测试一下

**Comment by 575610871** [comment]
该BUG已经解决，谢谢&nbsp;


图书馆精灵
***@***.***



&nbsp;
