### ISSUE TITLE
有时候点开软件不会显示头像, 是因为账号登录过期了?

### ISSUE THREAD

**Issue by HongJian-Yang** [leiurayer/downkyi#627]
有时候点开软件不会显示头像, 是因为账号登录过期了? 重新解压软件打开, 头像那的登录出来了,  登录的二维码加载不出来, 有没有人和我一样

**Comment by leiurayer** [comment]
看看日志

**Comment by HongJian-Yang** [comment]
> 看看日志

现在打开软件又看得见二维码了,不好复现

**Comment by Grey-Wind** [comment]
emm，我这里头像不能自动更新，换了好几次了，是要在软件里重登吗

**Comment by HongJian-Yang** [comment]
> 看看日志

是有个错误好像是什么IO buffer应该就是没读到图片, 日志我清掉了, 等下次遇到再发

**Comment by HongJian-Yang** [comment]
> emm，我这里头像不能自动更新，换了好几次了，是要在软件里重登吗


自动更新头像有啥用, 能正常下视频不就好了

**Comment by Grey-Wind** [comment]
> 自动更新头像有啥用, 能正常下视频不就好了

额，确实
只是看着老头像人难受

**Comment by HongJian-Yang** [comment]
> > 自动更新头像有啥用, 能正常下视频不就好了
> 
> 额，确实 只是看着老头像人难受

提个建议 让作者每次打开软件都刷一下个人资料吧

**Comment by Grey-Wind** [comment]
> 提个建议 让作者每次打开软件都刷一下个人资料吧

还要做一下不同窗口大小的适配，窗口一小所有数据都被压到一起了

**Comment by Grey-Wind** [comment]
额，但是，我进个人页面经常会显示不全

**Comment by HongJian-Yang** [comment]
> 额，但是，我进个人页面经常会显示不全

你屏幕分辨率多少?

**Comment by Grey-Wind** [comment]
1980 1080
