### ISSUE TITLE
分章节的视频只能解析第一个章节的视频

### ISSUE THREAD

**Issue by miaozilong** [leiurayer/downkyi#641]
示例链接：
https://www.bilibili.com/cheese/play/ss1380?csource=Hp_searchresult

第一章有3节视频
![image](https://user-images.githubusercontent.com/3994941/215997595-17cd11f3-619d-41e0-8c36-d27939b8aa67.png)
只解析了前3节视频

**Comment by leiurayer** [comment]
在程序中登录购买了此课程的账号，就可以解析剩余的视频了
