### ISSUE TITLE
麻烦请教下，编译报错

### ISSUE THREAD

**Issue by zhkingzh** [leiurayer/downkyi#652]
自己用vs2022编译，总是提示 这台计算机上缺少此项目引用的NuGet程序包，找不到程序包WebPSSharp等报错信息，我也设置NuGet的国内源地址了，按理说能自动下载程序包啊，但还是会报这个错，这是什么问题呢？（我是想自己编译下，改下载的默认选项，还有一些别的界面显示）

**Comment by leiurayer** [comment]
WebPSharp包在third_party里，手动添加下

**Comment by zhkingzh** [comment]
> WebPSharp包在third_party里，手动添加下

太感谢了，终于成功了
