### ISSUE TITLE
23年2月建立的收藏夹显示不出任何视频

### ISSUE THREAD

**Issue by gamepassonefloor** [leiurayer/downkyi#661]
网页展示正常，切换私密与公开都显示为空，只能读取有几页视频但是每页都是空，之前建立的收藏夹都能读出视频，这是什么情况

**Comment by LuckyBlock-Wellor** [comment]
同问

**Comment by wwwvvv113** [comment]
同样的问题。同样的情况。同上。

**Comment by AbraxasVi** [comment]
[DownKyi.zip](https://github.com/leiurayer/downkyi/files/11071537/DownKyi.zip)
VS2019社区版编译的，直接覆盖这俩文件就行
