### ISSUE TITLE
无法下载老视频

### ISSUE THREAD

**Issue by ColdCat-ship-it** [leiurayer/downkyi#664]
该视频为2018年的一些合集，年代有些久远，360P勉强观看。
不知道为什么这个视频无法下载，如图：
![image](https://user-images.githubusercontent.com/62545397/221356580-a8dd3f30-4ac3-4237-b0ca-5b61cfd75ec1.png)
非常感谢！

**Comment by uuttxt** [comment]
我也是这样，解决了吗

**Comment by ColdCat-ship-it** [comment]
> 我也是这样，解决了吗

先解析视频，我现在解决了，解析完就可以下载了
