### ISSUE TITLE
严重问题，差不多是2023.2.20后，个人空间新建的收藏夹显示无内容。

### ISSUE THREAD

**Issue by wwwvvv113** [leiurayer/downkyi#675]
严重问题，差不多是2023.2.20后，个人空间新建的收藏夹显示无内容。在B站收藏夹内有视频。在下载软件内进个人空间收藏夹内就无内容。以前建立的收藏夹无影响。时间差不多是2023.2.20这时间左右之后建立的收藏夹就无内容。能麻烦优先解决吗？切换收藏夹公开或者不公开都无内容。如图所示
![QQ拼音截图20230305215856](https://user-images.githubusercontent.com/33594561/222965004-0f522b9b-3922-4d3f-9901-646174f4e1e2.png)

**Comment by wwwvvv113** [comment]
![QQ拼音截图20230305215856](https://user-images.githubusercontent.com/33594561/222965044-a2f66c16-98ad-4e2b-9a81-bb629cafb083.png)

**Comment by leiurayer** [comment]
参看 #661 ，问题已解决，你可以pull代码自己编译，或者等下个版本发布
