### ISSUE TITLE
找不到可执行文件（exe）

### ISSUE THREAD

**Issue by AltriaAngel** [leiurayer/downkyi#697]
![image](https://user-images.githubusercontent.com/128955017/227757511-01da0dbd-8a2d-475e-886d-2a35962cd044.png)
不是杀毒软件的问题吧...我看github上这个路径下也没有exe但却依然有个“打不开DownKyi请点我.txt”，哪来的DownKyi，我怎么没看到（花了一个多小时甚至准备开始构建SLN开始编程？）

**Comment by Qixingchen** [comment]
去 release 中下载编译好的 zip.直接下代码那是源码当然没可运行文件.

**Comment by AltriaAngel** [comment]
> 



> 去 release 中下载编译好的 zip.直接下代码那是源码当然没可运行文件.

感谢，愧为计算机系学生【】
