### ISSUE TITLE
新建的收藏夹，看不到里面的视频，但是能正常显示里面的视频条数

### ISSUE THREAD

**Issue by Elewc** [leiurayer/downkyi#718]
![image](https://user-images.githubusercontent.com/11921414/232275054-6305e142-c354-4c35-b04b-b5a18f3c6dff.png)

**Comment by xisuo67** [comment]
这个问题必现吗？

**Comment by libb60** [comment]
我也是，只要是登陆后新建的收藏夹就都不显示视频详情，只显示视频条数

**Comment by Elewc** [comment]
新版本已经修复
