### ISSUE TITLE
默认收藏夹以外的部分收藏夹内容读取不到，显示为空

### ISSUE THREAD

**Issue by 1392600130** [leiurayer/downkyi#720]
能让这个功能实现吗，非常感谢

**Comment by 1392600130** [comment]
发现是一部分收藏夹无法读取，不是所有

**Comment by leiurayer** [comment]
比如说？哪些收藏夹读取不到

**Comment by 1392600130** [comment]
就是普通的收藏夹，分类里面的，我是第二个和第三个，第四个忘了有没有，右边视频栏显示为空，但是收藏夹名旁边会显示有几个视频
&nbsp;


海阔天空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月17日(星期一) 下午3:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [leiurayer/downkyi] 默认收藏夹以外的部分收藏夹内容读取不到，显示为空 (Issue #720)



比如说？哪些收藏夹读取不到

**Comment by iceschool** [comment]
+1，部分收藏夹加载为空，和权限没有关系，都处于【公开】状态

**Comment by xisuo67** [comment]
@1392600130 @iceschool 补充一下截图

**Comment by iceschool** [comment]
2023.4.22 11.47截图发自我的 iPhone在 2023年4月22日，09:46，初十 ***@***.***> 写道：﻿
@1392600130 @iceschool 补充一下截图
