### ISSUE TITLE
解析 up 的主页提示为空（附报错日志信息）

### ISSUE THREAD

**Issue by sankaki** [leiurayer/downkyi#722]
**软件启动后，在搜索框输入 https://space.bilibili.com/xxxxx/video 类似的地址，无法解析出来 up 的视频列表，查看后端日志有如下报错信息：**

2023年4月23日 星期日 15:43:30   [10]   DEBUG   AriaServer  [#98417a 0B/0B CN:1 DL:0B]
----------------------------------------------------------------------------------------------------------------------
2023年4月23日 星期日 15:43:31   [10]   DEBUG   AriaServer  [#98417a 0B/0B CN:1 DL:0B]
----------------------------------------------------------------------------------------------------------------------
2023年4月23日 星期日 15:43:32   [14]   ERROR   System  远程服务器返回错误: (412) Precondition Failed。
   在 System.Net.HttpWebRequest.GetResponse()
   在 DownKyi.Core.BiliApi.WebClient.RequestWeb(String url, String referer, String method, Dictionary`2 parameters, Int32 retry) 位置 D:\Study\computer\Csharp\DownKyi\develop2\DownKyi\DownKyi.Core\BiliApi\WebClient.cs:行号 82
----------------------------------------------------------------------------------------------------------------------
2023年4月23日 星期日 15:43:32   [15]   DEBUG   AriaServer  [#98417a 0B/0B CN:1 DL:0B]
----------------------------------------------------------------------------------------------------------------------
2023年4月23日 星期日 15:43:33   [14]   ERROR   System  远程服务器返回错误: (412) Precondition Failed。
   在 System.Net.HttpWebRequest.GetResponse()
   在 DownKyi.Core.BiliApi.WebClient.RequestWeb(String url, String referer, String method, Dictionary`2 parameters, Int32 retry) 位置 D:\Study\computer\Csharp\DownKyi\develop2\DownKyi\DownKyi.Core\BiliApi\WebClient.cs:行号 82
----------------------------------------------------------------------------------------------------------------------
2023年4月23日 星期日 15:43:33   [7]   DEBUG   AriaServer  [#98417a 0B/0B CN:1 DL:0B]
----------------------------------------------------------------------------------------------------------------------
2023年4月23日 星期日 15:43:34   [14]   ERROR   System  远程服务器返回错误: (412) Precondition Failed。
   在 System.Net.HttpWebRequest.GetResponse()
   在 DownKyi.Core.BiliApi.WebClient.RequestWeb(String url, String referer, String method, Dictionary`2 parameters, Int32 retry) 位置 D:\Study\computer\Csharp\DownKyi\develop2\DownKyi\DownKyi.Core\BiliApi\WebClient.cs:行号 82
----------------------------------------------------------------------------------------------------------------------
2023年4月23日 星期日 15:43:34   [15]   DEBUG   AriaServer  [#98417a 0B/0B CN:1 DL:0B]
----------------------------------------------------------------------------------------------------------------------

**Comment by xisuo67** [comment]
![image](https://user-images.githubusercontent.com/22284363/233830088-76f180fe-e0fd-42b7-a0cb-a41ecaae62aa.png)
![image](https://user-images.githubusercontent.com/22284363/233830209-a6bc0f5e-14e0-4db7-9434-e3285a36911e.png)
![image](https://user-images.githubusercontent.com/22284363/233830255-3835dab3-8c27-4781-9860-97b2b13684a8.png)
![image](https://user-images.githubusercontent.com/22284363/233830293-af2a0174-7bb7-417b-a1f7-ceaaaa63d233.png)

没复现，你什么版本？

**Comment by sankaki** [comment]
哎？奇怪，我尝试了您发布的最新版，和倒数第二个最新版，今天偶尔也会出现解析up主页视频为空，但是不会像昨天那么频繁了，我这边用的是福建电信的网络，账号开通了大会员，您可以多尝试解析不同 up 的地址，复现问题，好像是概率性的
