### ISSUE TITLE
解析视频，为何分辨率最高只有480P？

### ISSUE THREAD

**Issue by supwang** [leiurayer/downkyi#723]
解析视频，为何分辨率最高只有480P？
谢谢。

**Comment by Create-atom** [comment]
同问

**Comment by supwang** [comment]
> > 解析视频，为何分辨率最高只有480P？ 谢谢。
> 
> 登录一下就行

登录后可以看到1080P了，谢谢。
如果开通大会员，是否就能下载4K了？

**Comment by Create-atom** [comment]
> > > 解析视频，为何分辨率最高只有480P？ 谢谢。
> > 
> > 
> > 登录一下就行
> 
> 登录后可以看到1080P了，谢谢。 如果开通大会员，是否就能下载4K了？

经过测试，是可以的

**Comment by supwang** [comment]
> > > > 解析视频，为何分辨率最高只有480P？ 谢谢。
> > > 
> > > 
> > > 登录一下就行
> > 
> > 
> > 登录后可以看到1080P了，谢谢。 如果开通大会员，是否就能下载4K了？
> 
> 经过测试，是可以的

谢谢。
