### ISSUE TITLE
2023.4.29 最新版本1.5.7 已无法解析UP主主页全部视频链接，显示为空。

### ISSUE THREAD

**Issue by wwwvvv113** [leiurayer/downkyi#730]
2023.4.29 最新版本1.5.7 已无法解析UP主主页全部视频链接，显示为空。

**Comment by zhiben5201** [comment]
旧版本也不行了，应该不是版本的问题，是阿B更新了什么

**Comment by promiseMMD** [comment]
这个问题存在一段时间了  部分up主页能显示 部分不能

**Comment by leiurayer** [comment]
B站改api了，旧api被限制了访问次数

**Comment by wwwvvv113** [comment]
> B站改api了，旧api被限制了访问次数

大佬，用什么工具修改吗？我用notepad++，打开文件显示乱码。https://www.bilibili.com/video/BV1fT41187f7/?spm_id_from=333.999.0.0&vd_source=8209d25a7943c71b3c70678fc58423cd

**Comment by wwwvvv113** [comment]
> > B站改api了，旧api被限制了访问次数
> 
> 大佬，用什么工具修改吗？我用notepad++，打开文件显示乱码。
![image](https://user-images.githubusercontent.com/33594561/235361915-ca17d25b-80d0-4d35-ac45-35fe33939128.png)
