### ISSUE TITLE
播放列表部分视频解析失败

### ISSUE THREAD

**Issue by ziyuejun** [leiurayer/downkyi#732]
直接按照播放列表解析时，有几个视频一直无法解析，更换分辨率和音频质量都无效。https://www.bilibili.com/video/BV1Bs4y1D7Be/?spm_id_from=333.788&vd_source=83d035cde84be28ddf01d9bcdd95d822 
![image](https://user-images.githubusercontent.com/23349464/235347458-93a57c53-4287-4ffc-a311-c2d8195d9d84.png)

**Comment by leiurayer** [comment]
我这里测试可以解析出来
![image](https://user-images.githubusercontent.com/19290097/235347900-f82a3b40-6511-4125-8809-c7f198ebd626.png)

**Comment by ziyuejun** [comment]
好吧，我的问题，我把解析度码率调高试了下可以了
