### ISSUE TITLE
1.5.8进入UP主 主页，显示内容为空，测试多个UP主，都是这样。

### ISSUE THREAD

**Issue by jzmswe** [leiurayer/downkyi#733]
另：建议加个开关：是否启动downkyi后，自动开始下载。局域网内只能在24点后全速下载，系统计划任务设置好，到24点后自动启动downkyi.exe。就可以自动下载了，否则只是启动downkyi.exe，没有全部开始下载。
或者象utorrent那样，可以设置各个时段，不同下载速度也行。

**Comment by hsb0307** [comment]
可以提供批量视频号，然后批量下载吗 ？
