### ISSUE TITLE
1.5.5 和1.5.8 可以解析 但是 下载失败

### ISSUE THREAD

**Issue by chunjie008** [leiurayer/downkyi#736]
2023/5/4 10:10:44   [1]   DEBUG   NavigateToView  NavigationView: PageDownloadManager, Parameter: 
----------------------------------------------------------------------------------------------------------------------

**Comment by sycz** [comment]
同问 谢谢

**Comment by SCFState** [comment]
同问 感谢

**Comment by xisuo67** [comment]
@chunjie008 @sycz @SCFState 
提供一下链接，程序运行目录下log日志也贴一下
![image](https://user-images.githubusercontent.com/22284363/236679278-c88e11d5-687f-4595-8598-ddf7b5a1e487.png)

**Comment by SCFState** [comment]
@xisuo67  今天使用的时候又能正常下载了，原因不明，这是之前下载错误的log
```
2023/5/6 21:23:04   [1]   DEBUG   NavigateToView  NavigationView: PageUserSpace, Parameter: 1001749624
----------------------------------------------------------------------------------------------------------------------
2023/5/6 21:23:35   [1]   DEBUG   NavigateToView  NavigationView: PagePublication, Parameter: System.Collections.Generic.Dictionary`2[System.String,System.Object]
----------------------------------------------------------------------------------------------------------------------
2023/5/6 21:24:28   [1]   DEBUG   NavigateToView  NavigationView: PageSettings, Parameter: 
----------------------------------------------------------------------------------------------------------------------
2023/5/6 21:36:40   [17]   DEBUG   AriaDownloadService.DoWork()  下载服务结束
----------------------------------------------------------------------------------------------------
```

**Comment by sycz** [comment]
> @chunjie008 @sycz @SCFState 提供一下链接，程序运行目录下log日志也贴一下 ![image](https://user-images.githubusercontent.com/22284363/236679278-c88e11d5-687f-4595-8598-ddf7b5a1e487.png)

这也是我疑惑的地方，以前碰到问题在log中都能看到异常，可以自己排查解决。但是这次没有任何日志。。。
就跟@SCFState 看到的是一样的。

**Comment by chunjie008** [comment]
已经好了，什么也没动就好了，难道是b站改了协议又改回来了？
