### ISSUE TITLE
1.5.8版本，b站api是不是又改了，再次进不了up主个人空间

### ISSUE THREAD

**Issue by jsc093987jsc** [leiurayer/downkyi#753]
![image](https://github.com/leiurayer/downkyi/assets/133669298/46e995a4-ea58-4750-83fb-3dbebe2a8b96)

**Comment by Eyion** [comment]
不仅如此，而且解析出最高只有480P，原视频有1080P

**Comment by jsc093987jsc** [comment]
视频解析没有1080p是不是没有登录的原因

**Comment by ygzws** [comment]
一样的问题

**Comment by jsc093987jsc** [comment]
作者要不搞一个批量地址粘贴，批量下载的版本

**Comment by YaoYouGuan** [comment]
+1，发现了相同的情况。
