### ISSUE TITLE
用什么播放器？

### ISSUE THREAD

**Issue by aiodf** [leiurayer/downkyi#767]
如题，我该是用什么播放器才可以一起播放，弹幕与视屏

**Comment by leiurayer** [comment]
potplayer

**Comment by aiodf** [comment]
我想问一下，能设置弹幕显示区域吗？还有一个问题就是弹幕出现频闪。

**Comment by aiodf** [comment]
关于这个软件能否设置弹幕显示区域呢？全屏弹幕看不见内容了，但我又想借助弹幕 - -
