### ISSUE TITLE
想下64位的ffmpeg，不知道下哪一个阿？

### ISSUE THREAD

**Issue by Rimesal** [leiurayer/downkyi#795]
gpl、lgpl、master、n4、n5……选择困难症。

（我是win11家庭版

**Comment by Grey-Wind** [comment]
https://gitee.com/sunrise-studio/FFmpegUpdater

**Comment by Grey-Wind** [comment]
这玩意自动下载，还可以自动配置

**Comment by Rimesal** [comment]
> 

谢谢回复。
我是那天搜到一篇文章（https://zhuanlan.zhihu.com/p/554894140），讲的很清晰，最后下载了master＋gpl的版本。

**Comment by Grey-Wind** [comment]
> > 
> 
> 谢谢回复。
> 我是那天搜到一篇文章（https://zhuanlan.zhihu.com/p/554894140）
> 讲的很清晰，最后下载了master＋gpl的版本。

我感觉这个更新更方便
