### ISSUE TITLE
failed to bind TCP port 6800

### ISSUE THREAD

**Issue by wpy1533399** [leiurayer/downkyi#810]
具体报错信息，看图https://img1.imgtp.com/2023/07/12/p0Z1mk4b.png，报错信息传到图床了，几个版本都报这个错误，

**Comment by wpy1533399** [comment]
这个问题不用管了，是windows更新引起的问题，解决了

**Comment by Fihven** [comment]
怎么解决的

**Comment by leanna5462** [comment]
我也遇到了这个报错，然后把占用6800端口的进程关了就没问题了

**Comment by kv1830** [comment]
如果在cmd里面执行netstat -an | findstr 6800，看不到端口占用，但仍然有此问题。可以直接尝试重启一下。。。（尤其是如果之前用多个版本的切来切去的话）
