### ISSUE TITLE
关于下载姬解析视频的问题

### ISSUE THREAD

**Issue by jzfzzzz** [leiurayer/downkyi#887]
我在下一个番剧，能不能单独解析一个视频，而不是全部解析
![Snipaste_2023-10-29_11-43-56](https://github.com/leiurayer/downkyi/assets/107303455/2091cde5-8f9a-4a90-b1f1-3b4e7ba930fb)
像这种很多集的番剧，我还要等它全部解析完了才能下载，太慢了，能不能优化一下

**Comment by lingfengyu-dreaming** [comment]
应该是你设置的问题，去设置里面调一下解析范围

**Comment by jzfzzzz** [comment]
> 应该是你设置的问题，去设置里面调一下解析范围

哦是真的，设置里真的有这个选项，哈哈不好意思
