### ISSUE TITLE
解析B站视频只要流畅的清晰度

### ISSUE THREAD

**Issue by lekeshibai** [leiurayer/downkyi#894]
版本1.5.9
登录B站账号, 具有大会员
解析视频只有360P的流畅视频

**Comment by landall** [comment]
我这里看到的也是，只有480p的清晰度了。网站上视频是明确有1080p的。

**Comment by landall** [comment]
> 我这里看到的也是，只有480p的清晰度了。网站上视频是明确有1080p的。

晕，是登录到期了，没注意到……登录后就正常了。

**Comment by lekeshibai** [comment]
是吗,我重新登录看看.

**Comment by lekeshibai** [comment]
好吧, 我的登录没有到期, 但是退出账号之后重新登录也正常了. 感谢@landall
