### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by cepain** [leiurayer/downkyi#895]
在扫码界面会自动弹出”登录成功，3秒后自动跳转的提示“。需要反复点击登录按钮，在三秒内完成扫码并且卡进bug才能登录成功。

**Comment by Xiaoxiaoyu1321** [comment]
我也是一打开就“登录成功，3秒后自动跳转”，没法登录，但是为什么我卡bug卡不进去

**Comment by 2077418588** [comment]
我也是，特么的根本登陆不了！！！！作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了作者修一下啊求求求您了

**Comment by mataszhang** [comment]
我也是，特么的根本登陆不了！！！

**Comment by naijierubia** [comment]
打包的aria2程序为x86，下载x64程序手动更换后解决
https://leiurayer.github.io/downkyi/third_party/aria2-1.36.0-win-64bit-build1.zip

**Comment by Concohnb** [comment]
> 打包的aria2程序为x86，下载x64程序手动更换后解决 https://leiurayer.github.io/downkyi/third_party/aria2-1.36.0-win-64bit-build1.zip

更换了也没解决[狗头]

**Comment by yaobiao131** [comment]
#905

**Comment by mobzila** [comment]
![image](https://github.com/leiurayer/downkyi/assets/91730585/4f28a58c-8cf9-4738-a166-04025661709b)
我也是，直接下载会显示这样
