### ISSUE TITLE
退出后无法登陆或者无法加载登陆二维码，请求修复

### ISSUE THREAD

**Issue by th10010** [leiurayer/downkyi#905]
这几天downkyi退出登录后，尝试重新登陆有以下三种情况：
1.不加载登陆二维码；
2.加载了二维码未扫码的情况下自动登陆；
3.扫码后依然是未登录状态。
![微信截图_20231122094310](https://github.com/leiurayer/downkyi/assets/55772277/6fb1f54b-c7ff-43dc-9d3a-8b1785b83a48)

**Comment by kan20230309** [comment]
重新下 一个就好了  我一开始也这样

**Comment by wpillow87** [comment]
我也遇到的相同的问题,重新下载,重启电脑,依旧不能解决

**Comment by th10010** [comment]
> 重新下 一个就好了 我一开始也这样

试了下，依然如此，其实问题在于，扫码时，还没扫到或者确定登陆该设备，应用就开始跳转了

**Comment by th10010** [comment]
是不是现在b站不允许多设备登陆了，这几天每天会把我网页以及app踢下线

**Comment by yaobiao131** [comment]
我这边看是因为旧版api导致的，新版我已经提交pr，但是原作者没有合并。如果有能力可以使用我的pr自行编译

**Comment by th10010** [comment]
> 我这边看是因为旧版api导致的，新版我已经提交pr，但是原作者没有合并。如果有能力可以使用我的pr自行编译

感谢解答，配置了下，卡在编译环节了，说是找不到webpsharp 0.5.1，没能生成成功

**Comment by yaobiao131** [comment]
> > 我这边看是因为旧版api导致的，新版我已经提交pr，但是原作者没有合并。如果有能力可以使用我的pr自行编译
> 
> 感谢解答，配置了下，卡在编译环节了，说是找不到webpsharp 0.5.1，没能生成成功

nuget仓库的加一个到thirdparty目录的指向

**Comment by th10010** [comment]
> > > 我这边看是因为旧版api导致的，新版我已经提交pr，但是原作者没有合并。如果有能力可以使用我的pr自行编译
> > 
> > 
> > 感谢解答，配置了下，卡在编译环节了，说是找不到webpsharp 0.5.1，没能生成成功
> 
> nuget仓库的加一个到thirdparty目录的指向

搞定，谢谢大佬

**Comment by OLzzzz941** [comment]
评论区有人已经解决了，我还没看懂他们说了什么。所以是怎么弄得，求 解

**Comment by eecoder-dyf** [comment]
> > > 我这边看是因为旧版api导致的，新版我已经提交pr，但是原作者没有合并。如果有能力可以使用我的pr自行编译
> > 
> > 
> > 感谢解答，配置了下，卡在编译环节了，说是找不到webpsharp 0.5.1，没能生成成功
> 
> nuget仓库的加一个到thirdparty目录的指向

大佬能在你fork的仓库发一个release么

**Comment by eliswee** [comment]
我也遇到了

**Comment by always0807** [comment]
我也有这个问题，楼上的大佬们能发个修改过的下载么？实在看不懂太高端的，跪谢

**Comment by dtype2023** [comment]
可以了，谢谢大佬！

**Comment by eecoder-dyf** [comment]
> 临时发布了一个release https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9

感谢🙏

**Comment by always0807** [comment]
> 临时发布了一个release https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9

感谢！

**Comment by Sakura357** [comment]
> 临时发布了一个 release https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9

大佬，可以登录了，解析不了视频，怎么解决

**Comment by yaobiao131** [comment]
> > 临时发布了一个 release https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9
> 
> 大佬，可以登录了，解析不了视频，怎么解决

麻烦附上具体链接和现象

**Comment by Sakura357** [comment]
> > > 临时发布了一个 release https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9
> > 
> > 
> > 大佬，可以登录了，解析不了视频，怎么解决
> 
> 麻烦附上具体链接和现象

![Snipaste_20231129_164716](https://github.com/leiurayer/downkyi/assets/42261519/7ea9fc19-42c7-4e20-bd4e-abd37631234b)
只要是B站的视频解析都这样子

**Comment by FozuBlessNoBug** [comment]
我下载的1.5.9 点登录，依然看不到二维码

**Comment by STC214** [comment]
感谢 可以了

**Comment by Borrytod** [comment]
> 临时发布了一个release https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9

感谢大佬！！！

**Comment by hunterHungry** [comment]
> 临时发布了一个release https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9

可以了，感谢

**Comment by kevim31416** [comment]
> 临时发布了一个release https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9

網頁進不去
