### ISSUE TITLE
登陆自动跳转

### ISSUE THREAD

**Issue by hunterHungry** [leiurayer/downkyi#906]
1.5.9版本，点击登录，还没扫码，就登陆成功，然后自动跳转了

**Comment by lxianl455** [comment]
我也有一样的情况

**Comment by yaobiao131** [comment]
#896

**Comment by hunterHungry** [comment]
> #896

这个是源码，是用vs code编译一下就行了吗？语言是C#（不是程序员，只大致了解过编程，望解答）

**Comment by yaobiao131** [comment]
#905

**Comment by yaobiao131** [comment]
> 附议。扫码登陆登陆不上。1.5.8和1.5.9版本都登陆不上。并且登陆界面会自动3s跳转。

https://github.com/leiurayer/downkyi/issues/905#issuecomment-1827937695

**Comment by wulalayumao** [comment]
我也是一样，没办法登录
