### ISSUE TITLE
在下载设置窗口界面取消或关闭窗口之后导致的DownKyi闪退问题

### ISSUE THREAD

**Issue by coldgrasswow** [leiurayer/downkyi#907]
V1.5.9版本的DownKyi在*解析完了视频*且*点击“下载选中项”按钮弹出下载设置窗口后*，**一旦点击取消或关闭下载设置窗口，整个DownKyi工具就总是会一下子卡死并闪退，或者卡死成无响应状态需要任务管理器强制关闭才能摆脱掉其卡死状态**。

希望这个闪退BUG能让工具作者知晓一下，辛苦作者了！

**Comment by yaobiao131** [comment]
这个release应该修复了这个bug https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9

**Comment by coldgrasswow** [comment]
> 这个release应该修复了这个bug https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9

OK，1.6.0版本更新已经修复了我提到的这个BUG，谢谢作者了！
