### ISSUE TITLE
使用BUG

### ISSUE THREAD

**Issue by VMcsCat** [leiurayer/downkyi#91]
版本号：1.4.0
问题：在下载完成 视频、弹幕 后，系统默认不会加载此弹幕。  [https://ftp.bmp.ovh/imgs/2021/06/06206ad75ec2d767.png](url)
解决：将弹幕文件更改为与视频文件名称一致即可。    [https://ftp.bmp.ovh/imgs/2021/06/58a1a3c92f362903.png](url)

**Comment by FlySelfLog** [comment]
这不算bug，视频文件名带画质，弹幕文件名不带画质，所以本地播放器不能自动加载弹幕。
之所以这么设计，主要考虑到如果同一个视频下载了多个画质，那么弹幕文件名又应该带哪个画质呢？如果每个画质的视频都下载一个弹幕文件，又会重复下载。
开发时我会尽量避免重复请求B站API，一是降低被封ip的概率，二是减少B站服务器的压力。

**Comment by VMcsCat** [comment]
> 这不算，视频文件名带画质，弹幕文件名不带画质，所以本地播放器自动加载弹幕
> bug如果想一起设计，主要考虑到一个视频了那么弹幕文件名又应该带什么画质呢？如果画质的视频都下载一个弹幕文件，还会重复下载。
> 开发时我会尽量避免重复请求B站API，一是降低被封ip的诉说，二是减少B站的压力。

那可以出一个选项吗？比如说：[  ] 下载后的视频不带画质信息
