### ISSUE TITLE
is there some problems with login? 

### ISSUE THREAD

**Issue by linicall** [leiurayer/downkyi#910]
Is there some problems with login? I can't login, because when i haven't login, there's a QRcode showing,  and after 3 seconds, the QRcode disappear, and it's show i have been signed in but actually i dont't.

**Comment by yaobiao131** [comment]
https://github.com/leiurayer/downkyi/issues/905#issuecomment-1827937695

**Comment by linicall** [comment]
> [#905 (comment)](https://github.com/leiurayer/downkyi/issues/905#issuecomment-1827937695)



> [#905 (comment)](https://github.com/leiurayer/downkyi/issues/905#issuecomment-1827937695)

well, it's working

**Comment by BEE-gfc** [comment]
无法登录，点击登录后二维码显示一会儿，还没扫码就弹出来登陆成功，即使扫了码确认登陆也无法登录
