### ISSUE TITLE
打开之后弹出了这个窗口，能解析视频，但是不能下载

### ISSUE THREAD

**Issue by AzkzZz** [leiurayer/downkyi#917]
![Snipaste_2023-12-06_18-22-36](https://github.com/leiurayer/downkyi/assets/77612935/935b5885-9da0-45af-a421-8b5ffd4b7f00)

**Comment by yaobiao131** [comment]
这个多半端口被占用。你可以设置里面修改一下aria2端口，或者使用内建下载器
