### ISSUE TITLE
根本登录不了啊 ≧ ﹏ ≦

### ISSUE THREAD

**Issue by Jziumo** [leiurayer/downkyi#918]
![image](https://github.com/leiurayer/downkyi/assets/70738205/3fa308c3-9cb9-4b2e-8e81-b757d6eb224c)
点入登录界面后，大概是因为过了3s就会弹回主界面，我掐时间等着码跳出来直接扫再点登录也快不过3s。。不清楚是不是这就是原因，反正现在怎样都登不上去
我似大废员，想下载高清视频所以需要登录，请求修复谢谢🥰

**Comment by Glory-zrg** [comment]
我也有这样的情况，无法登陆

**Comment by Jziumo** [comment]
> 我也有这样的情况，无法登陆

你可以点击2楼的链接，里面有作者临时发布的一个版本下载，那个就可以登录了

**Comment by Jziumo** [comment]
> [#905 (comment)](https://github.com/leiurayer/downkyi/issues/905#issuecomment-1827937695)

谢谢大佬！已解决
