### ISSUE TITLE
使用旧版本1.4.0 @yaobiao131

### ISSUE THREAD

**Issue by kingjing337** [leiurayer/downkyi#922]
https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9 请问下，我如何使用旧版本的downkyi呢？
主要是旧版本可以不解析合集的列表，只自动解析单个视频，我特别需要这个功能。

麻烦@yaobiao131，能否做一个1.4.0可用版本呢？或者自己替换什么文件即可？

**Comment by yaobiao131** [comment]
能具体说一下两个版本的相关不同吗，因为我不了解旧版本



------------------ 原始邮件 ------------------
发件人: kingjing337 ***@***.***&gt;
发送时间: 2023年12月9日 02:55
收件人: leiurayer/downkyi ***@***.***&gt;
抄送: yaobiao131 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [leiurayer/downkyi] 使用旧版本1.4.0 @yaobiao131 (Issue #922)





 
https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9 请问下，我如何使用旧版本的downkyi呢？
 主要是旧版本可以不解析合集的列表，只自动解析单个视频，我特别需要这个功能。
 
***@***.***，能否做一个1.4.0可用版本呢？或者自己替换什么文件即可？

**Comment by kingjing337** [comment]
> 能具体说一下两个版本的相关不同吗，因为我不了解旧版本
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: kingjing337 ***@***.***&gt; 发送时间: 2023年12月9日 02:55 收件人: leiurayer/downkyi ***@***.***&gt; 抄送: yaobiao131 ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [leiurayer/downkyi] 使用旧版本1.4.0 @yaobiao131 (Issue #922) https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9 请问下，我如何使用旧版本的downkyi呢？ 主要是旧版本可以不解析合集的列表，只自动解析单个视频，我特别需要这个功能。 ***@***.***，能否做一个1.4.0可用版本呢？或者自己替换什么文件即可？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

1.4.0这个下载版本有两个好处：第一命名，如果我下载合集只需要勾选即可：
![1](https://github.com/leiurayer/downkyi/assets/44162854/811999c1-1118-403b-86b2-a77f6fc62728)

不用1.5.9复杂的命名规则。
第二合集下载，如果我只下载最新的一个视频，复制链接即刻解析：
![2](https://github.com/leiurayer/downkyi/assets/44162854/3bd5008c-b235-480a-a7c7-67cf0e2ebb23)

如上图所示，如果合集有几十上百个，如果是新版，我则需要等待几分钟甚至更长。

**Comment by yaobiao131** [comment]
你可以不打开自动解析视频就行了





------------------ 原始邮件 ------------------
发件人: kingjing337 ***@***.***&gt;
发送时间: 2023年12月9日 15:13
收件人: leiurayer/downkyi ***@***.***&gt;
抄送: yaobiao131 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [leiurayer/downkyi] 使用旧版本1.4.0 @yaobiao131 (Issue #922)





  
能具体说一下两个版本的相关不同吗，因为我不了解旧版本
 …
 ------------------ 原始邮件 ------------------ 发件人: kingjing337 @.&gt; 发送时间: 2023年12月9日 02:55 收件人: leiurayer/downkyi @.&gt; 抄送: yaobiao131 @.&gt;, Mention @.&gt; 主题: Re: [leiurayer/downkyi] 使用旧版本1.4.0 @yaobiao131 (Issue #922) https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9 请问下，我如何使用旧版本的downkyi呢？ 主要是旧版本可以不解析合集的列表，只自动解析单个视频，我特别需要这个功能。 @.，能否做一个1.4.0可用版本呢？或者自己替换什么文件即可？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt;
  
1.4.0这个下载版本有两个好处：第一命名，如果我下载合集只需要勾选即可：
 1.png (view on web)
 
不用1.5.9复杂的命名规则。
 第二合集下载，如果我只下载最新的一个视频，复制链接即刻解析：
 2.png (view on web)
 
如上图所示，如果合集有几十上百个，如果是新版，我则需要等待几分钟甚至更长。

**Comment by kingjing337** [comment]
> 你可以不打开自动解析视频就行了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: kingjing337 ***@***.***&gt; 发送时间: 2023年12月9日 15:13 收件人: leiurayer/downkyi ***@***.***&gt; 抄送: yaobiao131 ***@***.***&gt;, Mention ***@***.***&gt; 主题: Re: [leiurayer/downkyi] 使用旧版本1.4.0 @yaobiao131 (Issue #922) 能具体说一下两个版本的相关不同吗，因为我不了解旧版本 … ------------------ 原始邮件 ------------------ 发件人: kingjing337 @.&gt; 发送时间: 2023年12月9日 02:55 收件人: leiurayer/downkyi @.&gt; 抄送: yaobiao131 @.&gt;, Mention @.&gt; 主题: Re: [leiurayer/downkyi] 使用旧版本1.4.0 @yaobiao131 (Issue #922) https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9 请问下，我如何使用旧版本的downkyi呢？ 主要是旧版本可以不解析合集的列表，只自动解析单个视频，我特别需要这个功能。 @.，能否做一个1.4.0可用版本呢？或者自己替换什么文件即可？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.&gt; 1.4.0这个下载版本有两个好处：第一命名，如果我下载合集只需要勾选即可： 1.png (view on web) 不用1.5.9复杂的命名规则。 第二合集下载，如果我只下载最新的一个视频，复制链接即刻解析： 2.png (view on web) 如上图所示，如果合集有几十上百个，如果是新版，我则需要等待几分钟甚至更长。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

嗯嗯，我知道呢，但是这样做就得手动解析，会比较麻烦，而且如果是合集里最后一个文件，我也得顺序等待解析到最后一个才能下载。并且如果是单文件和合集切换下载，每次都得修改命名规则。请问下，1.4.0怎么做能够使用二维码呢？

**Comment by yaobiao131** [comment]
> > 你可以不打开自动解析视频就行了
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: kingjing337 _**@**_._**> 发送时间: 2023年12月9日 15:13 收件人: leiurayer/downkyi _**@**_.**_> 抄送: yaobiao131 _**@**_._**>, Mention _**@**_.**_> 主题: Re: [leiurayer/downkyi] 使用旧版本1.4.0 @yaobiao131 (Issue #922) 能具体说一下两个版本的相关不同吗，因为我不了解旧版本 … ------------------ 原始邮件 ------------------ 发件人: kingjing337 @.> 发送时间: 2023年12月9日 02:55 收件人: leiurayer/downkyi @.> 抄送: yaobiao131 @.>, Mention @.> 主题: Re: [leiurayer/downkyi] 使用旧版本1.4.0 @yaobiao131 (Issue #922) https://github.com/yaobiao131/downkyi/releases/tag/v1.5.9 请问下，我如何使用旧版本的downkyi呢？ 主要是旧版本可以不解析合集的列表，只自动解析单个视频，我特别需要这个功能。 @.，能否做一个1.4.0可用版本呢？或者自己替换什么文件即可？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.> 1.4.0这个下载版本有两个好处：第一命名，如果我下载合集只需要勾选即可： 1.png (view on web) 不用1.5.9复杂的命名规则。 第二合集下载，如果我只下载最新的一个视频，复制链接即刻解析： 2.png (view on web) 如上图所示，如果合集有几十上百个，如果是新版，我则需要等待几分钟甚至更长。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: _**@**_.***>
> 
> 嗯嗯，我知道呢，但是这样做就得手动解析，会比较麻烦，而且如果是合集里最后一个文件，我也得顺序等待解析到最后一个才能下载。并且如果是单文件和合集切换下载，每次都得修改命名规则。请问下，1.4.0怎么做能够使用二维码呢？

你可以选中你想下载的解析单个就行了，旧版应该不会再更新了

**Comment by kingjing337** [comment]
谢谢，我去问问作者把= =
