### ISSUE TITLE
大佬= =能不能把1.4.0修复下登录啊= =？

### ISSUE THREAD

**Issue by kingjing337** [leiurayer/downkyi#929]
我一直使用旧版本1.4.0，因为它很方便，不知道能不能修复下登录？
或者教下我怎么修复？

**Comment by leiurayer** [comment]
你从仓库的 v1.4.0 tag 拉一个分支，再把最近更新的修复登录代码复制过去编译

**Comment by kingjing337** [comment]
> 你从仓库的 v1.4.0 tag 拉一个分支，再把最近更新的修复登录代码复制过去编译

ok，我试试，哈哈哈哈

**Comment by ZC707** [comment]
> > 你从仓库的 v1.4.0 tag 拉一个分支，再把最近更新的修复登录代码复制过去编译
> 
> ok，我试试，哈哈哈哈

我也习惯了用v1.4.0，大佬能发个你修改好的下载么？实在是不会弄
