### ISSUE TITLE
再来报个闪退BUG

### ISSUE THREAD

**Issue by joeyreg** [leiurayer/downkyi#96]
测试链接：https://space.bilibili.com/258150656/video
选择全部，点第8页或第7页，全选，下载选中项，然后就会闪退

**Comment by FlySelfLog** [comment]
软件版本是1.4.0吗？是每次都会闪退吗？
我测试没有出现闪退的问题

**Comment by joeyreg** [comment]
> 软件版本是1.4.0吗？是每次都会闪退吗？
> 我测试没有出现闪退的问题
昨天确实有问题，今天好像没问题了，不过以前提过的问题现在还是偶尔会出现，比如某个UP主视频比较多，选择全部下载会在下到100个左的时候后面的视频全部不能下载出现重试，又无法重试，或者再次出现闪退，这个情况是不是被B站ban了？出现这种情况后网页看视频并没有什么问题。

**Comment by joeyreg** [comment]
> 软件版本是1.4.0吗？是每次都会闪退吗？
> 我测试没有出现闪退的问题

软件版本是1.4.0
