### ISSUE TITLE
建议：将弹幕的字幕文件与视频文件命名统一

### ISSUE THREAD

**Issue by HippieRocket** [leiurayer/downkyi#98]
在 `Downkyi` 下载完成后，所得的视频文件名结尾会标识清晰度，但所得弹幕的文件名结尾没有。在 `VLC` 播放器中，如果视频文件和字幕文件同名则可自动添加字幕，否则只能手动添加。如果**将弹幕的字幕文件与视频文件命名统一**将更为方便。

感谢开发者为我们带来这么棒的软件，一直以来辛苦了。

**Comment by Gerald-Chen** [comment]
没有提前看到 #91 真的很抱歉，给各位造成困扰了 :sob:
