### ISSUE TITLE
希望增加HDR 真彩清晰度的支持

### ISSUE THREAD

**Issue by yunshenwuji** [leiurayer/downkyi#993]
感谢作者大大持续维护这个优秀的项目，如题，希望能增加对HDR 真彩清晰度的支持。
HDR 真彩清晰度的影片可以看下这个视频，里面有这个清晰度的选项
https://www.bilibili.com/bangumi/play/ss39865

**Comment by yaobiao131** [comment]
> 感谢作者大大持续维护这个优秀的项目，如题，希望能增加对HDR 真彩清晰度的支持。 HDR 真彩清晰度的影片可以看下这个视频，里面有这个清晰度的选项 https://www.bilibili.com/bangumi/play/ss39865

网页并没有看到hdr在哪

**Comment by yaobiao131** [comment]
> 感谢作者大大持续维护这个优秀的项目，如题，希望能增加对HDR 真彩清晰度的支持。 HDR 真彩清晰度的影片可以看下这个视频，里面有这个清晰度的选项 https://www.bilibili.com/bangumi/play/ss39865

设置里面设置优先画质。就会解析hdr的画质了

**Comment by yunshenwuji** [comment]
抱歉抱歉，是我不会用了
