### ISSUE TITLE
最新版本1.6.1无法解析视频

### ISSUE THREAD

**Issue by 321yida** [leiurayer/downkyi#998]
软件替换过aria2和ffmpeg版本
![image](https://github.com/leiurayer/downkyi/assets/67246596/73ca2fc6-f187-4c06-9137-69f96f7258d2)
![image](https://github.com/leiurayer/downkyi/assets/67246596/caee909c-c620-4cc3-bf19-25083a422391)
在下载如下视频时解析失败
![image](https://github.com/leiurayer/downkyi/assets/67246596/e94d72c3-16da-48af-8b28-aa98bc903bc5)

解析失败后查看日志如下
![image](https://github.com/leiurayer/downkyi/assets/67246596/e071f65b-b1f8-40ad-8194-299433a14b0d)

**Comment by yaobiao131** [comment]
参考 https://github.com/leiurayer/downkyi/issues/983#issuecomment-1867544330

**Comment by 321yida** [comment]
修改ua为Mozilla/5.0已解决
