### ISSUE TITLE
视频下载封面出错

### ISSUE THREAD

**Issue by 321yida** [leiurayer/downkyi#999]
视频链接https://www.bilibili.com/video/BV1wp4y1d7FR/
![image](https://github.com/leiurayer/downkyi/assets/67246596/d2bf13df-d7cc-4426-a88e-1b6abe2b3277)
在最新版本1.6.1中粘贴链接，下载如下两个视频，
![image](https://github.com/leiurayer/downkyi/assets/67246596/414f9943-6e20-4f71-89bb-9f99747dcae5)
默认的文件命名格式归类如下
![image](https://github.com/leiurayer/downkyi/assets/67246596/167164be-d0e8-4903-b8fd-01cc1988076c)
就会造成封面下载错误，封面都是输入链接视频的封面
![image](https://github.com/leiurayer/downkyi/assets/67246596/6eac7de6-c1d0-4d89-bda9-a72ac5a7e616)
两个视频均会归类到 链接视频 的 视频标题 文件夹下，这种归类方式也不是很好。

**Comment by yaobiao131** [comment]
https://github.com/leiurayer/downkyi/pull/965/commits/ddba2d7d4fbcd7dbb2bd2c1e26bc76f1d6da6922
在本次提交中已修复。只是目前没有合并你可以参考 https://github.com/leiurayer/downkyi/issues/983#issuecomment-1867544330

**Comment by 321yida** [comment]
> [ddba2d7](https://github.com/leiurayer/downkyi/commit/ddba2d7d4fbcd7dbb2bd2c1e26bc76f1d6da6922) 在本次提交中已修复。只是目前没有合并你可以参考 [#983 (comment)](https://github.com/leiurayer/downkyi/issues/983#issuecomment-1867544330)

好的，感谢大佬
